services:
    _defaults:
        autowire: true
        public: true
        autoconfigure: true

    Vich\UploaderBundle\Storage\FlysystemStorage: ~
    Chamilo\CoreBundle\Repository\ResourceFactory: ~
    Chamilo\CoreBundle\Repository\ResourceNodeRepository: ~

    # Classic entity repositories
    Chamilo\CoreBundle\Repository\:
        resource: '../../Repository'
        exclude: '../../Repository/{BranchSyncRepository.php,ResourceRepository.php}'
        tags: ['doctrine.repository_service']

    # Resource repositories
#    Chamilo\CoreBundle\Repository\AccessUrlRepository:
#        arguments:
#            $className: 'Chamilo\CoreBundle\Entity\AccessUrl'

#    Chamilo\CoreBundle\Repository\CourseRepository:
#        arguments:
#            $className: 'Chamilo\CoreBundle\Entity\Course'
#
#    Chamilo\CoreBundle\Repository\IllustrationRepository:
#        arguments:
#            $className: 'Chamilo\CoreBundle\Entity\Illustration'
#
#    Chamilo\CoreBundle\Repository\PersonalFileRepository:
#        arguments:
#            $className: 'Chamilo\CoreBundle\Entity\PersonalFile'

    Chamilo\CoreBundle\Repository\UserRepository:
        calls:
            - [setEncoder, ['@security.user_password_encoder.generic']]

    Chamilo\CoreBundle\Repository\GroupRepository: ~
