services:
    _defaults:
        autowire: true
        public: true
        autoconfigure: true

    Vich\UploaderBundle\Storage\FlysystemStorage: ~
#    Chamilo\CoreBundle\Repository\ResourceFactory: ~
    Chamilo\CoreBundle\Repository\ResourceNodeRepository: ~

#    Chamilo\CoreBundle\Repository\ResourceRepository:
#        abstract: true
#        calls:
#            - setAuthorizationChecker: ['@security.authorization_checker']
#            - setRouter: ['@router']
#            - setSlugify: [Cocur\Slugify\Slugify]

    # Classic entity repositories
    Chamilo\CoreBundle\Repository\:
        resource: '../../Repository'
        exclude: '../../Repository/{Node,ResourceRepository.php,BranchSyncRepository.php}'
        tags: ['doctrine.repository_service']

    Chamilo\CoreBundle\Repository\Node\:
        resource: '../../Repository/Node'
        calls:
            - setAuthorizationChecker: ['@security.authorization_checker']
            - setRouter: ['@router']
            - setSlugify: ['@cocur_slugify']
            - setToolChain: ['@Chamilo\CoreBundle\ToolChain']
            - setResourceNodeRepository: ['@Chamilo\CoreBundle\Repository\ResourceNodeRepository']
        tags: ['doctrine.repository_service']

    # Resource repositories
#    Chamilo\CoreBundle\Repository\Node\AccessUrlRepository:
#        arguments:
#            $className: 'Chamilo\CoreBundle\Entity\AccessUrl'

#    Chamilo\CoreBundle\Repository\Node\CourseRepository:
#        arguments:
#            $className: 'Chamilo\CoreBundle\Entity\Course'
#
#    Chamilo\CoreBundle\Repository\Node\IllustrationRepository:
#        arguments:
#            $className: 'Chamilo\CoreBundle\Entity\Illustration'
#
#    Chamilo\CoreBundle\Repository\PersonalFileRepository:
#        arguments:
#            $className: 'Chamilo\CoreBundle\Entity\PersonalFile'

    Chamilo\CoreBundle\Repository\Node\UserRepository:
        calls:
            - setEncoder: ['@security.user_password_encoder.generic']
            - setAuthorizationChecker: [ '@security.authorization_checker' ]
            - setRouter: [ '@router' ]
            - setSlugify: [ '@cocur_slugify' ]
            - setToolChain: [ '@Chamilo\CoreBundle\ToolChain' ]
            - setResourceNodeRepository: [ '@Chamilo\CoreBundle\Repository\ResourceNodeRepository' ]

    Chamilo\CoreBundle\Repository\GroupRepository: ~
