# Settings parameters that will be used in the 'services' section
parameters:
    chamilo_core.entity.manager.session_manager.class: Chamilo\CoreBundle\Entity\Manager\SessionManager
    chamilo_core.entity.session: Chamilo\CoreBundle\Entity\Session

services:
    _defaults:
        autowire: true
        public: true
        autoconfigure: true

    chamilo_core.translation.loader.po:
        class: Symfony\Component\Translation\Loader\PoFileLoader
        tags:
            - {name: translation.loader, alias: po}

    Chamilo\CoreBundle\:
        resource: '../../*'
        exclude: '../../{Repository,Tool,Admin,Block,Component,Composer,DependencyInjection,EventListener,Form,Framework,Menu,Migrations,Settings,ChamiloCoreBundle.php,Entity,Tests}'
        public: true

    Chamilo\CoreBundle\Controller\:
        resource: '../../Controller'
        tags: ['controller.service_arguments']

    apy_grid.factory:
        class: APY\DataGridBundle\Grid\GridFactory
        arguments: ['@service_container', '@apy_grid.registry']

    APY\DataGridBundle\Grid\Grid: '@grid'

    menu.voter.regex:
        class: Chamilo\CoreBundle\Menu\MenuVoter
        arguments: ['@request_stack']
        tags:
            - {name: knp_menu.voter}

    # Entity managers
    chamilo_core.entity.manager.session_manager:
        class: '%chamilo_core.entity.manager.session_manager.class%'
        arguments: ['%chamilo_core.entity.session%', '@doctrine']

    # Chamilo Twig extension (already added with autowiring)
#    twig.extension.chamilo_extension:
#        class: Chamilo\CoreBundle\Twig\Extension\ChamiloExtension
#        tags:
#            - {name: twig.extension}

#    twig.extension.date:
#        class: Twig_Extensions_Extension_Date
#        tags:
#            - { name: twig.extension }

    Chamilo\CoreBundle\Security\Encoder:
        arguments:
            - '%password_encryption%'

    # User image naming
#    chamilo_core.naming.user_image:
#        class: Chamilo\CoreBundle\Naming\UserImage
    # Form types
    # Custom yes/no form type, use in the platform settings
    chamilo_core.form.type.yes_no:
        class: Chamilo\CoreBundle\Form\Type\YesNoType
        tags:
            - {name: form.type, alias: yes_no}
#    # Extra field attribute services
#    chamilo_user.form.type.attribute_value_type:
#        class: Chamilo\CoreBundle\Form\Type\AttributeValueType
#        arguments: [Chamilo\CoreBundle\Entity\ExtraFieldValues, ['registration'], 'user', @sylius.repository.subject_name_attribute_value]
#        tags:
#            - {name: form.type, alias: chamilo_user_extra_field_value}
##
#
#    chamilo_user.form.type.attribute_type:
#        class: Chamilo\CoreBundle\Form\Type\AttributeType
#        arguments: [Chamilo\CoreBundle\Entity\ExtraField, ['registration'], 'user']
##        arguments: [%sylius.attribute.attribute_types%]
#        tags:
#            - {name: form.type, alias: chamilo_user_attribute_type}
#
#    chamilo_user.form.type.attribute_choice_type:
#        class: Chamilo\CoreBundle\Form\Type\AttributeTypeChoiceType
#        arguments: [%sylius.attribute.attribute_types%]
#        tags:
#            - {name: form.type, alias: chamilo_user_attribute_choice}
    # html editor
    chamilo_core.html_editor:
        class: Chamilo\CoreBundle\Component\Editor\CkEditor\CkEditor
        arguments: ['@translator', '@router']

    # Check if users are online
#    chamilo_core.listener.online:
#        class: Chamilo\CoreBundle\EventListener\OnlineListener
#        arguments: [@security.context, @doctrine.orm.entity_manager ]
#        tags:
#            - {name: kernel.event_listener, event: kernel.controller, method: onCoreController}

    Chamilo\CoreBundle\Entity\Listener\ResourceListener:
        tags:
            - {name: doctrine.orm.entity_listener, entity_manager: default, lazy: true}

    Chamilo\CoreBundle\Entity\Listener\ResourceNodeListener:
        tags:
            - {name: doctrine.orm.entity_listener, entity_manager: default, lazy: true}

    Chamilo\CoreBundle\Entity\Listener\SessionListener:
        tags:
            - {name: doctrine.orm.entity_listener, entity_manager: default, lazy: true}

    chamilo_course.listener.course:
        class: Chamilo\CoreBundle\EventListener\CourseListener
        calls:
            - [setContainer, ['@service_container']]
        tags:
            - {name: kernel.event_listener, event: kernel.request, method: onKernelRequest, priority: 6}
            - {name: kernel.event_listener, event: kernel.response, method: onKernelResponse}
            - {name: kernel.event_listener, event: kernel.controller, method: onKernelController}

    # Sets the user access in a course listener
    chamilo_course.listener.course_access:
        class: Chamilo\CoreBundle\EventListener\CourseAccessListener
        arguments:
            - '@doctrine.orm.entity_manager'
        calls:
            - [setRequest, ['@request_stack']]
        tags:
            - {name: kernel.event_listener, event: chamilo_course.course.access, method: onCourseAccessEvent}

    # Sets the user access in a course session listener
    chamilo_course.listener.session_access:
        class: Chamilo\CoreBundle\EventListener\SessionAccessListener
        arguments:
            - '@doctrine.orm.entity_manager'
        calls:
            - [setRequest, ['@request_stack']]
        tags:
            - {name: kernel.event_listener, event: chamilo_course.course.session, method: onSessionAccessEvent}

    # When Course entity is loaded
    chamilo_core.listener.course:
        class: Chamilo\CoreBundle\Entity\Listener\CourseListener
        arguments: ['@Chamilo\CourseBundle\Repository\CToolRepository', '@Chamilo\CoreBundle\ToolChain', '@chamilo.settings.manager']
        tags:
            - {name: doctrine.orm.entity_listener, entity_manager: default, lazy: true}

    # Setting user
    chamilo_core.listener.legacy:
        class: Chamilo\CoreBundle\EventListener\LegacyListener
        calls:
            - [setContainer, ['@service_container']]
        tags:
            - {name: kernel.event_listener, event: kernel.request, method: onKernelRequest, priority: 7}
            - {name: kernel.event_listener, event: kernel.response, method: onKernelResponse}
            - {name: kernel.event_listener, event: kernel.controller, method: onKernelController}

    # Locale listener
    chamilo_core.listener.locale:
        class: Chamilo\CoreBundle\EventListener\LocaleListener
        arguments: ['%kernel.default_locale%', '@service_container']
        tags:
            - {name: kernel.event_subscriber, priority: 15}

    # User locale listener
    Chamilo\CoreBundle\EventListener\UserLocaleListener:
        tags:
            - {name: kernel.event_listener, event: security.interactive_login, method: onInteractiveLogin, priority: 15}

    # Settings listener
    chamilo_core.listener.settings:
        class: Chamilo\CoreBundle\EventListener\SettingListener
        arguments: ['@service_container']
        tags:
            - {name: kernel.event_listener, event: sylius.settings.pre_save, method: onSettingPreSave}

    Chamilo\CoreBundle\EventListener\TwigListener:
        tags:
            - {name: kernel.event_listener}

#    # Menu listener
#    chamilo_core.listener.navbar_menu_listener:
#        class: Chamilo\CoreBundle\EventListener\MenuListener
#        arguments: ['@service_container']
#        tags:
#            - {name: kernel.event_listener, event: theme.sidebar_left_menu, method: onSetupMenu}
#            - {name: kernel.event_listener, event: theme.breadcrumb, method: onSetupMenu}

#    chamilo_core.listener.navbar_user_listener:
#        class: Chamilo\CoreBundle\EventListener\ShowUserListener
#        arguments: ['@service_container']
#        tags:
#            - {name: kernel.event_listener, event: theme.navbar_user, method: onShowUser}
#            - {name: kernel.event_listener, event: theme.sidebar_user, method: onShowUser}

    # Menu
#    chamilo_core.listener.message_listener:
#        class: Chamilo\CoreBundle\EventListener\MessageListener
#        arguments: ['@service_container']
#        tags:
#            - {name: kernel.event_listener, event: theme.messages, method: onListMessages}

    # Course upload listener
    chamilo_core.listener.resource_upload_listener:
        class: Chamilo\CoreBundle\EventListener\ResourceUploadListener
        arguments: ['@router']
        tags:
            - {name: kernel.event_listener, event: oneup_uploader.post_persist, method: onUpload}

    chamilo_core.menu.nav_builder:
        class: Chamilo\CoreBundle\Menu\NavBuilder
        arguments:
            - '@knp_menu.factory'
            - '@security.authorization_checker'
        calls:
            - [setContainer, ['@service_container']]
        tags:
#            - {name: mopa_bootstrap.menu, alias: chamilo_core.menu.nav}
            - {name: knp_menu.menu_builder, method: menuApp, alias: menuApp}

#    chamilo_core.menu.course_menu_builder:
#        class: Chamilo\CoreBundle\Menu\LeftMenuBuilder
#        calls:
#            - [setContainer, ['@service_container']]
#        tags:
#            - {name: mopa_bootstrap.menu, alias: chamilo_core.left.nav}

    # Auth listeners
    chamilo_core.listener.login_success_handler:
        class: Chamilo\CoreBundle\EventListener\LoginSuccessHandler
        arguments: ['@router', '@security.authorization_checker', '@chamilo.settings.manager']
        tags:
            - {name: kernel.event_listener, event: security.interactive_login, method: onSecurityInteractiveLogin}

    chamilo_core.listener.logout_success_handler:
        class: Chamilo\CoreBundle\EventListener\LogoutSuccessHandler
        arguments: ['@router', '@security.authorization_checker', '@security.token_storage']

    Chamilo\CoreBundle\Twig\SettingsHelper:
        arguments:
            - '@chamilo.settings.manager'
        tags:
            - {name: templating.helper, alias: chamilo_settings}

    Liip\ImagineBundle\Service\FilterService:
        alias: 'liip_imagine.service.filter'
