# Settings parameters that will be used in the 'services' section
services:
    _defaults:
        autowire: true
        public: true
        autoconfigure: true

    chamilo_core.translation.loader.po:
        class: Symfony\Component\Translation\Loader\PoFileLoader
        tags:
            - {name: translation.loader, alias: po}

    Chamilo\CoreBundle\:
        resource: '../../*'
        exclude: '../../{Repository,Tool,Admin,Block,Component,Composer,DependencyInjection,EventListener,Form,Framework,Menu,Migrations,Settings,ChamiloCoreBundle.php,Entity,Tests}'
        public: true

    Chamilo\CoreBundle\Controller\:
        resource: '../../Controller'
        tags: ['controller.service_arguments']

#    twig.extension.date:
#        class: Twig_Extensions_Extension_Date
#        tags:
#            - { name: twig.extension }
    # User image naming
#    chamilo_core.naming.user_image:
#        class: Chamilo\CoreBundle\Naming\UserImage
    # Form types
    # Custom yes/no form type, use in the platform settings
    chamilo_core.form.type.yes_no:
        class: Chamilo\CoreBundle\Form\Type\YesNoType
        tags:
            - {name: form.type, alias: yes_no}
#    # Extra field attribute services
#    chamilo_user.form.type.attribute_value_type:
#        class: Chamilo\CoreBundle\Form\Type\AttributeValueType
#        arguments: [Chamilo\CoreBundle\Entity\ExtraFieldValues, ['registration'], 'user', @sylius.repository.subject_name_attribute_value]
#        tags:
#            - {name: form.type, alias: chamilo_user_extra_field_value}
##
#
#    chamilo_user.form.type.attribute_type:
#        class: Chamilo\CoreBundle\Form\Type\AttributeType
#        arguments: [Chamilo\CoreBundle\Entity\ExtraField, ['registration'], 'user']
##        arguments: [%sylius.attribute.attribute_types%]
#        tags:
#            - {name: form.type, alias: chamilo_user_attribute_type}
#
#    chamilo_user.form.type.attribute_choice_type:
#        class: Chamilo\CoreBundle\Form\Type\AttributeTypeChoiceType
#        arguments: [%sylius.attribute.attribute_types%]
#        tags:
#            - {name: form.type, alias: chamilo_user_attribute_choice}
    # html editor
    chamilo_core.html_editor:
        class: Chamilo\CoreBundle\Component\Editor\CkEditor\CkEditor
        arguments: ['@translator', '@router']

    # Check if users are online
#    chamilo_core.listener.online:
#        class: Chamilo\CoreBundle\EventListener\OnlineListener
#        arguments: [@security.context, @doctrine.orm.entity_manager ]
#        tags:
#            - {name: kernel.event_listener, event: kernel.controller, method: onCoreController}

    Chamilo\CoreBundle\Repository\AssetRepository: ~

    Chamilo\CoreBundle\EventListener\AssetListener:
        arguments:
            - '@Chamilo\CoreBundle\Repository\AssetRepository'
        tags:
            - {name: kernel.event_listener, event: vich_uploader.post_remove}

    Chamilo\CoreBundle\Entity\Listener\ResourceListener:
        tags:
            - {name: doctrine.orm.entity_listener, entity_manager: default, lazy: true}

    Chamilo\CoreBundle\Entity\Listener\ResourceNodeListener:
        tags:
            - {name: doctrine.orm.entity_listener, entity_manager: default, lazy: true}

    Chamilo\CoreBundle\Entity\Listener\SessionListener:
        tags:
            - {name: doctrine.orm.entity_listener, entity_manager: default, lazy: true}

    Chamilo\CoreBundle\EventListener\CourseListener:
        calls:
            - [setContainer, ['@service_container']]
        tags:
            - {name: kernel.event_listener, event: kernel.request, method: onKernelRequest, priority: 6}
            - {name: kernel.event_listener, event: kernel.response, method: onKernelResponse}
            - {name: kernel.event_listener, event: kernel.controller, method: onKernelController}

    # Sets the user access in a course listener
    Chamilo\CoreBundle\EventListener\CourseAccessListener:
        arguments:
            - '@doctrine.orm.entity_manager'
        calls:
            - [setRequest, ['@request_stack']]
        tags:
            - {name: kernel.event_listener, event: chamilo_course.course.access, method: onCourseAccessEvent}

    # Sets the user access in a course session listener
    Chamilo\CoreBundle\EventListener\SessionAccessListener:
        arguments:
            - '@doctrine.orm.entity_manager'
        calls:
            - [setRequest, ['@request_stack']]
        tags:
            - {name: kernel.event_listener, event: chamilo_course.course.session, method: onSessionAccessEvent}

    # When the Course entity is created/updated
    Chamilo\CoreBundle\Entity\Listener\CourseListener:
        arguments: ['@Chamilo\CoreBundle\ToolChain', '@chamilo.settings.manager']
        tags:
            - {name: doctrine.orm.entity_listener, entity_manager: default, lazy: true}

    # When the User entity is created/updated        -
    Chamilo\CoreBundle\Entity\Listener\UserListener:
        arguments: ['@Chamilo\CoreBundle\Repository\Node\UserRepository']
        tags:
            - {name: doctrine.orm.entity_listener, entity_manager: default, lazy: true}

    # Setting user
    Chamilo\CoreBundle\EventListener\LegacyListener:
        calls:
            - [setContainer, ['@service_container']]
        tags:
            - {name: kernel.event_listener, event: kernel.request, method: onKernelRequest, priority: 7}
            - {name: kernel.event_listener, event: kernel.response, method: onKernelResponse}
            - {name: kernel.event_listener, event: kernel.controller, method: onKernelController}

    # Locale listener
    Chamilo\CoreBundle\EventSubscriber\LocaleSubscriber:
        arguments: ['%kernel.default_locale%', '@chamilo.settings.manager', '@parameter_bag']

    # User locale listener
#    Chamilo\CoreBundle\EventListener\UserLocaleListener:
#        tags:
#            - {name: kernel.event_listener, event: security.interactive_login, method: onInteractiveLogin, priority: 15}

    # Settings listener
    Chamilo\CoreBundle\EventListener\SettingListener:
        arguments: ['@service_container']
        tags:
            - {name: kernel.event_listener, event: sylius.settings.pre_save, method: onSettingPreSave}

    Chamilo\CoreBundle\EventListener\TwigListener:
        tags:
            - {name: kernel.event_listener}

    # Course upload listener
    Chamilo\CoreBundle\EventListener\ResourceUploadListener:
        arguments: ['@router']
        tags:
            - {name: kernel.event_listener, event: oneup_uploader.post_persist, method: onUpload}

    # Auth listeners
    chamilo_core.listener.login_success_handler:
        class: Chamilo\CoreBundle\EventListener\LoginSuccessHandler
        arguments: ['@router', '@security.authorization_checker', '@chamilo.settings.manager']
        tags:
            - {name: kernel.event_listener, event: security.interactive_login, method: onSecurityInteractiveLogin}

    Chamilo\CoreBundle\EventListener\LogoutListener:
        tags:
            - name: kernel.event_listener
              event: Symfony\Component\Security\Http\Event\LogoutEvent
              dispatcher: security.event_dispatcher.main
              priority: 20

    Chamilo\CoreBundle\Twig\SettingsHelper:
        arguments:
            - '@chamilo.settings.manager'
        tags:
            - {name: templating.helper, alias: chamilo_settings}
