services:
    _defaults:
        autowire: false
        public: true
        autoconfigure: false

    # Tool chain loads the list of tool services with the tag "chamilo_core.tool"
    # Tool chain is filled in file DependencyInjection/Compiler/ToolCompilerClass.php
    Chamilo\CoreBundle\ToolChain: ~

    # Global
    chamilo_core.tool.global:
        class: Chamilo\CoreBundle\Tool\GlobalTool
        arguments:
            - 'global'
            - ''
            - ''
            - ''
            -
                urls:
                    repository: Chamilo\CoreBundle\Repository\AccessUrlRepository
                courses:
                    repository: Chamilo\CoreBundle\Repository\CourseRepository
                users:
                    repository: Chamilo\UserBundle\Repository\UserRepository
            - 1
        tags:
            - {name: chamilo_core.tool}

    chamilo_core.tool.asset:
        class: Chamilo\CoreBundle\Tool\Asset
        arguments:
            - 'asset'
            - ''
            - ''
            - ''
            -
                illustrations:
                    repository: Chamilo\CoreBundle\Repository\IllustrationRepository
            - 1
        tags:
            - {name: chamilo_core.tool}

    # Agenda tool
    chamilo_core.tool.agenda:
        class: Chamilo\CoreBundle\Tool\Agenda
        arguments:
            - 'agenda'
            - 'authoring'
            - 'calendar/agenda.php'
            - chamilo_course.settings.agenda
            -
                events:
                    repository: Chamilo\CourseBundle\Repository\CCalendarEventRepository
                event_attachments:
                    repository: Chamilo\CourseBundle\Repository\CCalendarEventAttachmentRepository
            - 0
        tags:
            - {name: chamilo_core.tool}

    # Announcement tool
    chamilo_core.tool.announcement:
        class: Chamilo\CoreBundle\Tool\Announcement
        arguments:
            - 'announcement'
            - 'authoring'
            - 'announcements/announcements.php'
            - '@chamilo_course.settings.announcement'
            -
                announcements:
                    repository: Chamilo\CourseBundle\Repository\CAnnouncementRepository
                announcements_attachments:
                    repository: Chamilo\CourseBundle\Repository\CAnnouncementAttachmentRepository
            - 0
        tags:
            - {name: chamilo_core.tool}

    chamilo_core.tool.assignment:
        class: Chamilo\CoreBundle\Tool\Assignment
        arguments:
            - 'student_publication'
            - 'interaction'
            - 'work/work.php'
            - chamilo_course.settings.assignment
            -
                student_publications:
                    repository: Chamilo\CourseBundle\Repository\CStudentPublicationRepository
                student_publications_assignments:
                    repository: Chamilo\CourseBundle\Repository\CStudentPublicationAssignmentRepository
            - 0
        tags:
            - {name: chamilo_core.tool}

    chamilo_core.tool.attendance:
        class: Chamilo\CoreBundle\Tool\Attendance
        arguments:
            - 'attendance'
            - 'authoring'
            - 'attendance/index.php'
            - '@chamilo_course.settings.attendance'
            -
                attendances:
                    repository: Chamilo\CourseBundle\Repository\CAttendanceRepository
            - 0
        tags:
            - {name: chamilo_core.tool}

    chamilo_core.tool.blog:
        class: Chamilo\CoreBundle\Tool\Blog
        arguments:
            - 'blog'
            - 'admin'
            - 'blog/blog_admin.php'
            - '@chamilo_course.settings.blog'
            -
                blogs:
                    repository: Chamilo\CourseBundle\Repository\CBlogRepository
            - 0
        tags:
            - {name: chamilo_core.tool}

    chamilo_core.tool.course_description:
        class: Chamilo\CoreBundle\Tool\CourseDescription
        arguments:
            - course_description
            - authoring
            - course_description/index.php
            - '@chamilo_course.settings.course_description'
            -
                course_descriptions:
                    repository: Chamilo\CourseBundle\Repository\CCourseDescriptionRepository
            - 0
        tags:
            - {name: chamilo_core.tool}

    chamilo_core.tool.chat:
        class: Chamilo\CoreBundle\Tool\Chat
        arguments:
            - chat
            - interaction
            - chat/chat.php
            - '@chamilo_course.settings.chat'
            - ~
            - 0
        tags:
            - {name: chamilo_core.tool}

    chamilo_core.tool.course_progress:
        class: Chamilo\CoreBundle\Tool\CourseProgress
        arguments:
            - course_progress
            - authoring
            - course_progress/index.php
            - '@chamilo_course.settings.course_progress'
            -
                thematics:
                    repository: Chamilo\CourseBundle\Repository\CThematicRepository
                thematic_advance:
                    repository: Chamilo\CourseBundle\Repository\CThematicAdvanceRepository
                thematic_plans:
                    repository: Chamilo\CourseBundle\Repository\CThematicPlanRepository
            - 0
        tags:
            - {name: chamilo_core.tool}

    chamilo_core.tool.document:
        class: Chamilo\CoreBundle\Tool\Document
        arguments:
            - document
            - authoring
            - document/document.php
            - '@chamilo_course.settings.document'
            -
                files:
                    repository: Chamilo\CourseBundle\Repository\CDocumentRepository
            - 0
        tags:
            - {name: chamilo_core.tool}

    chamilo_core.tool.dropbox:
        class: Chamilo\CoreBundle\Tool\Dropbox
        arguments:
            - dropbox
            - interaction
            - dropbox/index.php
            - '@chamilo_course.settings.dropbox'
            -
                dropbox:
                    repository: Chamilo\CourseBundle\Repository\CDropboxRepository
            - 0
        tags:
            - {name: chamilo_core.tool}

    chamilo_core.tool.exercise:
        class: Chamilo\CoreBundle\Tool\Exercise
        arguments:
            - quiz
            - authoring
            - exercise/exercise.php
            - '@chamilo_course.settings.exercise'
            -
                exercises:
                    repository: Chamilo\CourseBundle\Repository\CQuizRepository
                questions:
                    repository: Chamilo\CourseBundle\Repository\CQuizQuestionRepository
                question_categories:
                    repository: Chamilo\CourseBundle\Repository\CQuizQuestionCategoryRepository
                exercise_categories:
                    repository: Chamilo\CourseBundle\Repository\CExerciseCategoryRepository
            - 0
        tags:
            - {name: chamilo_core.tool}

    chamilo_core.tool.forum:
        class: Chamilo\CoreBundle\Tool\Forum
        arguments:
            - forum
            - interaction
            - forum/index.php
            - '@chamilo_course.settings.forum'
            -
                forums:
                    repository: Chamilo\CourseBundle\Repository\CForumRepository
                forum_attachments:
                    repository: Chamilo\CourseBundle\Repository\CForumAttachmentRepository
                forum_categories:
                    repository: Chamilo\CourseBundle\Repository\CForumCategoryRepository
                forum_posts:
                    repository: Chamilo\CourseBundle\Repository\CForumPostRepository
                forum_threads:
                    repository: Chamilo\CourseBundle\Repository\CForumThreadRepository
            - 0
        tags:
            - {name: chamilo_core.tool}

    chamilo_core.tool.glossary:
        class: Chamilo\CoreBundle\Tool\Glossary
        arguments:
            - glossary
            - authoring
            - glossary/index.php
            - '@chamilo_course.settings.glossary'
            -
                glossaries:
                    repository: Chamilo\CourseBundle\Repository\CGlossaryRepository
            - 0
        tags:
            - {name: chamilo_core.tool}

    chamilo_core.tool.gradebook:
        class: Chamilo\CoreBundle\Tool\Gradebook
        arguments:
            - gradebook
            - authoring
            - gradebook/index.php
            - '@chamilo_course.settings.gradebook'
            -
                gradebook_categories:
                    repository: Chamilo\CourseBundle\Repository\CGradebookCategoryRepository
                gradebook_links:
                    repository: Chamilo\CourseBundle\Repository\CGradebookLinkRepository
                gradebook_evaluations:
                    repository: Chamilo\CourseBundle\Repository\CGradebookEvaluationRepositor

            - 0
        tags:
            - {name: chamilo_core.tool}

    chamilo_core.tool.group:
        class: Chamilo\CoreBundle\Tool\Group
        arguments:
            - 'group'
            - 'interaction'
            - 'group/group.php'
            - '@chamilo_course.settings.group'
            -
                groups:
                    repository: Chamilo\CourseBundle\Repository\CGroupInfoRepository
                group_categories:
                    repository: Chamilo\CourseBundle\Repository\CGroupCategoryRepository
                gradebook_evaluations:
                    repository: Chamilo\CourseBundle\Repository\CGradebookEvaluationRepository
            - 0
        tags:
            - {name: chamilo_core.tool}

    chamilo_core.tool.learning_path:
        class: Chamilo\CoreBundle\Tool\LearningPath
        arguments:
            - 'learnpath'
            - 'authoring'
            - 'lp/lp_controller.php'
            - '@chamilo_course.settings.learning_path'
            -
                lps:
                    repository: Chamilo\CourseBundle\Repository\CLpCategory
                lp_categories:
                    repository: Chamilo\CourseBundle\Repository\CLpCategoryRepository
            - 0
        tags:
            - {name: chamilo_core.tool}

    chamilo_core.tool.link:
        class: Chamilo\CoreBundle\Tool\Link
        arguments:
            - 'link'
            - 'authoring'
            - 'link/link.php'
            - '@chamilo_course.settings.link'
            -
                links:
                    repository: Chamilo\CourseBundle\Repository\CLinkRepository
                link_categories:
                    repository: Chamilo\CourseBundle\Repository\CLinkRepository
            - 0
        tags:
            - {name: chamilo_core.tool}

    # Maintenance
    chamilo_course.settings.maintenance:
        class: Chamilo\CourseBundle\Settings\MaintenanceCourseSettingsSchema
        tags:
            - {name: chamilo_course.settings_schema, alias: chamilo_course.settings.maintenance, namespace: maintenance}

    chamilo_core.tool.member:
        class: Chamilo\CoreBundle\Tool\Member
        arguments:
            - 'member'
            - 'interaction'
            - 'user/user.php'
            - '@chamilo_course.settings.user'
            - ~
            - 0
        tags:
            - {name: chamilo_core.tool}

    chamilo_core.tool.maintenance:
        class: Chamilo\CoreBundle\Tool\Maintenance
        arguments:
            - 'course_maintenance'
            - 'admin'
            - 'course_info/maintenance.php'
            - '@chamilo_course.settings.maintenance'
            - ~
            - 0
        tags:
            - {name: chamilo_core.tool}

    chamilo_core.tool.notebook:
        class: Chamilo\CoreBundle\Tool\Notebook
        arguments:
            - 'notebook'
            - 'interaction'
            - 'notebook/index.php'
            - '@chamilo_course.settings.notebook'
            -
                notebooks:
                    repository: Chamilo\CourseBundle\Repository\CNotebookRepository
            - 0
        tags:
            - {name: chamilo_core.tool}

    chamilo_core.tool.settings:
        class: Chamilo\CoreBundle\Tool\Settings
        arguments:
            - 'course_setting'
            - admin
            - course_info/infocours.php
            - '@chamilo_course.settings.settings'
            - ~
            - 0
        tags:
            - {name: chamilo_core.tool}

    # Survey
    chamilo_core.tool.survey:
        class: Chamilo\CoreBundle\Tool\Survey
        arguments:
            - 'survey'
            - 'interaction'
            - 'survey/survey_list.php'
            - '@chamilo_course.settings.survey'
            -
                surveys:
                    repository: Chamilo\CourseBundle\Repository\CSurveyRepository
                survey_questions:
                    repository: Chamilo\CourseBundle\Repository\CSurveyQuestionRepository
            - 0
        tags:
            - {name: chamilo_core.tool}

    chamilo_core.tool.tracking:
        class: Chamilo\CoreBundle\Tool\Tracking
        arguments:
            - tracking
            - admin
            - tracking/courseLog.php
            - '@chamilo_course.settings.tracking'
            - ~
            - 0
        tags:
            - {name: chamilo_core.tool}

    chamilo_core.tool.user:
        class: Chamilo\CoreBundle\Tool\User
        arguments:
            - user
            - interaction
            - ~
            - ~
            -
                files:
                    repository: Chamilo\CoreBundle\Repository\PersonalFileRepository
            - 0
        tags:
            - {name: chamilo_core.tool}

    chamilo_core.tool.wiki:
        class: Chamilo\CoreBundle\Tool\Wiki
        arguments:
            - wiki
            - interaction
            - wiki/index.php
            - '@chamilo_course.settings.wiki'
            -
                wikis:
                    repository: Chamilo\CourseBundle\Repository\CWikiRepository
            - 0
        tags:
            - {name: chamilo_core.tool}
