api_platform:
    title: 'Chamilo Api'
    version: '1.0.0'
    mapping:
        paths: ['%kernel.project_dir%/src/CoreBundle/Entity', '%kernel.project_dir%/src/CourseBundle/Entity']
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
    formats:
        jsonld:
            mime_types: ['application/ld+json']
        json:
            mime_types: ['application/json']
        html:
            mime_types: ['text/html']
        graphql:
            mime_types: ['application/graphql']
    collection:
        pagination:
            items_per_page_parameter_name: itemsPerPage # Default value
    defaults:
        pagination_client_items_per_page: true
#    mercure:
#        hub_url: '%env(MERCURE_SUBSCRIBE_URL)%'
