doctrine_migrations:
    migrations_paths:
        'Chamilo\CoreBundle\Migrations\Schema\V200': '%kernel.project_dir%/src/CoreBundle/Migrations/Schema/V200'

    all_or_nothing: true
    check_database_platform: true