fos_user:
    db_driver: orm # can be orm or odm
    firewall_name: secured_area

    # if you change the class configuration, please also alter the sonata_user.yml file
    user_class: Chamilo\UserBundle\Entity\User

    group:
        group_class: Chamilo\UserBundle\Entity\Group
        group_manager: sonata.user.orm.group_manager

    service:
        user_manager: sonata.user.orm.user_manager

    from_email:
        address: 'test@example.com'
        sender_name: 'test@example.com'