#fos_rest:
#    routing_loader:
#        include_format: false
#    param_fetcher_listener: true
#    format_listener:
#        rules:
#            - {path: '^/api2', priorities:['json'], fallback_format: json, prefer_extension: false}
#            - {path: '^/', priorities: ['html', '*/*'], fallback_format: ~, prefer_extension: true}
#    view:
#        view_response_listener: true
#        formats:
#            json: true

#    body_listener: true
#    body_converter:
#        enabled: true
#        validate: true
#        validation_errors_argument: validationErrors
