framework:
    form: true
    secret: '%env(APP_SECRET)%'
    csrf_protection: true
    #esi: ~
    #fragments: ~
    php_errors:
        log: true
    templating:
        engines: ['twig']
    session:
#        # handler_id set to null will use default session handler from php.ini
#        handler_id:  session.handler.native_file
#        save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%'
        name: chamilo2
    http_method_override: true
    annotations:
        cache: file
        file_cache_dir: "%kernel.cache_dir%/annotations"
    serializer: { enable_annotations: true }