overblog_graphql:
    definitions:
        schema:
            query: Query
            mutation: Mutation
            resolver_maps:
                - Chamilo\ApiBundle\GraphQL\Map\RootMap
                - Chamilo\ApiBundle\GraphQL\Map\UserMap
                - Chamilo\ApiBundle\GraphQL\Map\EnumMap
                - Chamilo\ApiBundle\GraphQL\Map\ScalarMap
                - Chamilo\ApiBundle\GraphQL\Map\MutationMap
        mappings:
            types:
                -
                    type: graphql
                    dir: "%kernel.root_dir%/ApiBundle/GraphQL/Resources/config"

services:
    Chamilo\ApiBundle\GraphQL\:
        resource: "../../src/ApiBundle/GraphQL/*"
        arguments:
            - "@service_container"
