overblog_graphql:
    definitions:
        schema:
            query: Query
            resolver_maps:
                - Chamilo\ApiBundle\GraphQL\Map\RootResolverMap
                - Chamilo\ApiBundle\GraphQL\Map\UserResolverMap
                - Chamilo\ApiBundle\GraphQL\Map\EnumResolverMap
                - Chamilo\ApiBundle\GraphQL\Map\ScalarResolverMap
        mappings:
            types:
                -
                    type: graphql
                    dir: "%kernel.root_dir%/ApiBundle/GraphQL/Resources/config"
