# The LiipImagineBundle can be used if you want to convert on demand an image
# to a specific format. (ie a controller render the file)
# more information can be found here : https://github.com/liip/LiipImagineBundle

liip_imagine:
    resolvers:
        default:
            web_path:
                cache_prefix: '../var/cache/resource'
    loaders:
        resources:
            filesystem:
                data_root: '%kernel.project_dir%/var/upload/resource'
    filter_sets:
        # Chamilo filters
        hotspot_question:
            quality: 75
            filters:
                relative_resize: {widen: 800} # keep aspect ratio to width
