lunetics_locale:
  guessing_order:
    - query
    - session
    - cookie
    - browser
    - router
  switcher:
    show_current_locale: true
  allowed_locales:  #  From DB table languages
    - 'ar'
    - 'ast'
    - 'eu'
    - 'bn'
    - 'bs'
    - 'pt-BR'
    - 'bg'
    - 'ca'
    - 'hr'
    - 'cs'
    - 'da'
    - 'prs'
    - 'nl'
    - 'en'
    - 'eo'
    - 'fo'
    - 'fi'
    - 'fr'
    - 'fur'
    - 'gl'
    - 'ka'
    - 'de'
    - 'el'
    - 'he'
    - 'hi'
    - 'hu'
    - 'id'
    - 'it'
    - 'ja'
    - 'ko'
    - 'lv'
    - 'lt'
    - 'mk'
    - 'ms'
    - 'no'
    - 'oc'
    - 'ps'
    - 'fa'
    - 'pl'
    - 'pt'
    - 'qu'
    - 'ro'
    - 'ru'
    - 'sr'
    - 'zh'
    - 'sk'
    - 'sl'
    - 'so'
    - 'es'
    - 'sw'
    - 'sv'
    - 'tl'
    - 'th'
    - 'bo'
    - 'zh-TW'
    - 'tr'
    - 'uk'
    - 'vi'
    - 'xh'
    - 'yo'
