oneup_flysystem:
    adapters:
        courses_adapter:
            local:
                directory: '%kernel.project_dir%/var/courses'

        home_adapter:
            local:
                directory: '%kernel.project_dir%/var/home'

#        s3.adapter:
#              awss3v3:
#                  client: s3_client # add service "s3_client"
#                  bucket: ~
#                  prefix: ~
    filesystems:
        courses:
            adapter: courses_adapter
            visibility: private
            cache: ~
            alias: ~
            mount: ~

        home:
            adapter: home_adapter
            visibility: private
            alias: home_filesystem