oneup_flysystem:
    cache:
        my_cache:
            memory: ~
    adapters:
        asset_adapter:
            local:
                directory: '%kernel.project_dir%/var/upload/assets'
        resource_adapter:
            local:
                directory: '%kernel.project_dir%/var/upload/resource'
        resource_cache_adapter:
            local:
                directory: '%kernel.project_dir%/var/cache/resource'
    filesystems:
        assets:
            adapter: asset_adapter
            mount: assets_fs
        resources:
            adapter: resource_adapter
            mount: resources_fs
            visibility: private
        cache_resources:
            adapter: resource_cache_adapter
            mount: cache_resources_fs
            visibility: private
