oneup_flysystem:
    adapters:
        resource_adapter:
            local:
                directory: '%kernel.project_dir%/var/upload/resource'

    filesystems:
        resources:
            adapter: resource_adapter
            mount: resources_fs
            visibility: private
