oneup_flysystem:
    adapters:
        asset_adapter:
            local:
                location: '%kernel.project_dir%/var/upload/assets'
        resource_adapter:
            local:
                location: '%kernel.project_dir%/var/upload/resource'
        resource_cache_adapter:
            local:
                location: '%kernel.project_dir%/var/cache/resource'
    filesystems:
        asset:
            adapter: asset_adapter
            mount: asset
        resource:
            adapter: resource_adapter
            mount: resource
            visibility: private
        resource_cache:
            adapter: resource_cache_adapter
            mount: resource_cache
            visibility: private
