oneup_flysystem:
    adapters:
        courses_adapter:
            local:
                directory: '%kernel.project_dir%/var/courses'

        home_adapter:
            local:
                directory: '%kernel.project_dir%/var/home'

        upload_adapter:
            local:
                directory: '%kernel.project_dir%/var/upload'

    filesystems:
        courses:
            adapter: courses_adapter
            visibility: private
            cache: ~
            alias: ~
            mount: ~

        home:
            adapter: home_adapter
            visibility: private
            alias: home_filesystem

        upload:
            adapter: upload_adapter
