# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
    #enable_authenticator_manager: true

    password_hashers:
        Chamilo\CoreBundle\Entity\User:
            algorithm: auto

    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        app_user_provider:
            entity:
                class: Chamilo\CoreBundle\Entity\User
                property: username
    role_hierarchy:
        ROLE_ADMIN:
            - ROLE_SUPER_ADMIN # Admin that install the platform
            - ROLE_QUESTION_MANAGER
            - ROLE_SESSION_MANAGER
            - ROLE_TEACHER
            - ROLE_CURRENT_COURSE_TEACHER
            - ROLE_CURRENT_COURSE_SESSION_TEACHER
            - ROLE_CURRENT_COURSE_GROUP_TEACHER
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]
        ROLE_GLOBAL_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]
        ROLE_RRHH: [ROLE_TEACHER, ROLE_ALLOWED_TO_SWITCH]
        ROLE_TEACHER: [ROLE_STUDENT]
        ROLE_QUESTION_MANAGER: [ROLE_STUDENT, ROLE_QUESTION_MANAGER]
        ROLE_SESSION_MANAGER: [ROLE_STUDENT, ROLE_SESSION_MANAGER, ROLE_ALLOWED_TO_SWITCH]
        ROLE_STUDENT: [ROLE_STUDENT]
        ROLE_CURRENT_COURSE_STUDENT: [ROLE_CURRENT_COURSE_STUDENT] # Set in the CourseListener
        ROLE_CURRENT_COURSE_TEACHER: [ROLE_CURRENT_COURSE_TEACHER, ROLE_CURRENT_COURSE_STUDENT] # Set in the course listener
        ROLE_CURRENT_COURSE_GROUP_STUDENT: [ROLE_CURRENT_COURSE_GROUP_STUDENT] # Set in the CourseListener
        ROLE_CURRENT_COURSE_GROUP_TEACHER: [ROLE_CURRENT_COURSE_GROUP_TEACHER, ROLE_CURRENT_COURSE_GROUP_STUDENT]
        ROLE_CURRENT_COURSE_SESSION_STUDENT: [ROLE_CURRENT_COURSE_SESSION_STUDENT]
        ROLE_CURRENT_COURSE_SESSION_TEACHER: [ROLE_CURRENT_COURSE_SESSION_STUDENT, ROLE_CURRENT_COURSE_SESSION_TEACHER]
        ROLE_ANONYMOUS: [ROLE_ANONYMOUS]
    #access_decision_manager:
        # strategy can be: affirmative, unanimous or consensus
        # only grant access if none of the voters has denied access
        #strategy: unanimous
    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
            anonymous: true

        # Use to connect via a JWT token
        api:
            pattern: ^/api
            stateless: false
            context: main
            anonymous: true
            provider: app_user_provider
            json_login:
                check_path: /api/authentication_token
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator

        # Default login via json
        main:
            pattern: ^/
            context: main
            provider: app_user_provider
            anonymous: true
#            login_throttling:
#                max_attempts: 5
            #            form_login:
            #                csrf_token_generator: security.csrf.token_manager
            #                login_path: /login
            #                use_forward: false
            #                check_path: /login
            #                failure_path: null
            guard:
                authenticators:
                    - Chamilo\CoreBundle\Security\LoginFormAuthenticator
#                    - Chamilo\CoreBundle\Security\TokenAuthenticator

            entry_point: Chamilo\CoreBundle\Security\AuthenticationEntryPoint
            remember_me:
                secret: '%secret%'
                lifetime: 604800 # 1 week in seconds
                path: /
            logout:
                path: /logout
                target: /
            switch_user: true
            #            access_denied_handler: Chamilo\CoreBundle\Security\AccessDeniedHandler
            json_login:
                check_path: /login_json
                # username_path: security.credentials.login
                # password_path: security.credentials.password

    access_control:
        #        - {path: ^/administrator, role: ROLE_ADMIN}
        #        - {path: ^/efconnect, role: ROLE_USER}
        #        - {path: ^/elfinder, role: ROLE_USER}
#        - { path: ^/login, roles: PUBLIC_ACCESS }
#        - { path: ^/api/authentication_token, roles: PUBLIC_ACCESS }
        - { path: ^/login, roles: PUBLIC_ACCESS }
        - { path: ^/api/authentication_token, roles: PUBLIC_ACCESS }
#        - {path: ^/login, roles: PUBLIC_ACCESS}
#        - {path: ^/api/authentication_token, roles: PUBLIC_ACCESS}