twig:
    paths: ['%kernel.project_dir%/templates']
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    exception_controller: 'FOS\RestBundle\Controller\ExceptionController::showAction'
    globals:
        show_toolbar: true
        show_footer: true
        software_name: Chamilo
        version: 2
        session_teachers:
        teachers:
        news_counter:
        news_list:
        messages_count:
        message_link:
        is_profile_editable:
        administrator_name:
        execution_stats:
        course_session_block:
        show_course_shortcut:
        show_course_navigation_menu:
        actions:
        header:
        message:
        show_media_element: 1
