version: "2"
  checks:
    file-lines:
      enabled: false

plugins:
  fixme:
    enabled: true
    config:
      strings:
      - FIXME
      - BUG

  phpcodesniffer:
    enabled: true
    config:
      standard: "PSR1,PSR2"
      file_extensions: "php"
    checks:
      PSR1 Classes ClassDeclaration MissingNamespace:
        enabled: false
      PSR1 Files SideEffects FoundWithSymbols:
        enabled: false

  phpmd:
      enabled: true
      config:
        file_extensions: "php"

  sonar-php:
    enabled: true

  duplication:
    enabled: true

exclude_patterns:
- cli-config.php
- app/cache/
- app/logs/
- app/config/
- app/SymfonyRequirements.php
- app/Migrations/
- app/Resources/
- main/admin/db.php
- main/admin/ldap_synchro.php
- main/auth/cas/lib/
- main/auth/shibboleth
- main/auth/openid
- main/chat/emoji_strategy.php
- main/default_course_document
- main/document/Wami.swf
- main/fonts/
- main/inc/ajax/Wami.swf
- main/inc/lib/browser/
- main/inc/lib/freemindflashbrowser/
- main/inc/lib/internationalization_database/
- main/inc/lib/javascript/
- main/inc/lib/kses-0.2.2/
- main/inc/lib/mimetex/
- main/inc/lib/nanogong/
- main/inc/lib/nusoap/
- main/inc/lib/ppt2png/
- main/inc/lib/pear/
- main/inc/lib/phpmailer/
- main/inc/lib/phpseclib/
- main/inc/lib/portfolio.class.php
- main/inc/lib/svg-edit/
- main/inc/lib/swfobject/
- main/inc/lib/wami-recorder/
- main/inc/lib/xajax/
- main/lp/packaging/
- main/template/
- main/img/
- main/lang/
- plugin/buycourses/src/Culqi/
- plugin/buycourses/src/Requests/
- plugin/buycourses/src/Requests.php
- plugin/buycourses/src/paypalfunctions.php
- plugin/kannelsms/vendor/
- plugin/clockworksms/vendor/
- plugin/pens/lib
- plugin/bbb/lib/bbb_api.php
- plugin/ims_lti/OAuthSimple.php
- plugin/sepe/src/wsse/
- tests/
- vendor/
- web/
