version: "2"
checks:
  argument-count:
    enabled: false
  complex-logic:
    enabled: false
  file-lines:
    enabled: false
  method-complexity:
    enabled: true
    config:
      threshold: 20
  method-count:
    enabled: false
  method-lines:
    enabled: false
  nested-control-flow:
    config:
      threshold: 20
  return-statements:
    enabled: false

plugins:
  phan:
    enabled: true
    config:
      file_extensions: "php"

  fixme:
    enabled: true
    config:
      strings:
      - FIXME
      - BUG

  phpcodesniffer:
    enabled: true
    config:
      standard: "Symfony2"
      file_extensions: "php"
    checks:
      PSR1 Classes ClassDeclaration MissingNamespace:
        enabled: false
      PSR1 Files SideEffects FoundWithSymbols:
        enabled: false
      Squiz Strings ConcatenationSpacing PaddingFound:
        enabled: false

  phpmd:
    enabled: true
    config:
      file_extensions: "php"
      rulesets: "ruleset.xml"

  sonar-php:
    enabled: false
    checks:
      php:S1192:
        enabled: false

  duplication:
    enabled: false

exclude_patterns:
  - var/cache/
  - var/log/
  - config/
  - public/main/admin/db.php
  - public/main/admin/ldap_synchro.php
  - public/main/chat/emoji_strategy.php
  - public/main/document/Wami.swf
  - public/main/fonts/
  - public/main/inc/ajax/Wami.swf
  - public/main/inc/lib/browser/
  - public/main/inc/lib/internationalization_database/
  - public/main/inc/lib/javascript/
  - public/main/inc/lib/kses-0.2.2/
  - public/main/inc/lib/mimetex/
  - public/main/inc/lib/nanogong/
  - public/main/inc/lib/nusoap/
  - public/main/inc/lib/opengraph/*
  - public/main/inc/lib/ppt2png/
  - public/main/inc/lib/pear/
  - public/main/inc/lib/svg-edit/
  - public/main/inc/lib/swfobject/
  - public/main/inc/lib/wami-recorder/
  - public/main/inc/lib/xajax/
  - public/main/lp/packaging/
  - public/main/template/
  - public/main/lang/
  - public/libs/
  - public/img/
  - plugin/buycourses/src/Culqi/
  - plugin/buycourses/src/Requests/
  - plugin/buycourses/src/Requests.php
  - plugin/buycourses/src/paypalfunctions.php
  - plugin/vchamilo/cli/
  - plugin/pens/lib
  - plugin/bbb/lib/bbb_api.php
  - plugin/ims_lti/OAuthSimple.php
  - plugin/sepe/src/wsse/
  - plugin/test2pdf/class/
  - plugin/jcapture/lib/
  - plugin/jcapture/src/
  - tests/
  - vendor/
  - web/
