engines:
  phpcodesniffer:
    enabled: true
    config:
    standard: "PSR1,PSR2"
  phpmd:
    enabled: true
  duplication:
  	enabled: true
    config:
    	languages:
      - php

ratings:
  paths:
  - '*.php'

exclude_paths:
- 'app/cache/*'
- 'app/logs/*'
- 'app/Migrations/*'
- 'main/admin/db.php'
- 'main/auth/cas/lib/CAS/*'
- 'main/inc/lib/browser/*'
- 'main/inc/lib/elfinder/*'
- 'main/inc/lib/freemindflashbrowser/*'
- 'main/inc/lib/kses-0.2.2/*'
- 'main/inc/lib/mimetex/*'
- 'main/inc/lib/nanogong/*'
- 'main/inc/lib/pclzip/*'
- 'main/inc/lib/pear/*'
- 'main/inc/lib/phpmailer/*'
- 'main/inc/lib/phpseclib/*'
- 'main/inc/lib/svg-edit/*'
- 'main/inc/lib/swfobject/*'
- 'main/inc/lib/wami-recorder/*'
- 'main/inc/lib/xajax/*'
- 'main/img/*'
- 'main/lang/*'
- 'tests/*'
- 'vendor/*'
- 'web/*'