dist: bionic
language: php
php:
  7.2
  #    7.3

addons:
  apt:
    packages:
      - apache2
      - postfix
      - libappindicator1
      - fonts-liberation

services:
  - mysql
  - xvfb

cache:
  yarn: true
  directories:
    - $HOME/.composer/cache/files

matrix:
  fast_finish: false
  include:
    - php: 7.2
    #- php: 7.3

env:
  global:
    - VHOST_URL=localhost
    - CHAMILO_VERSION=master

before_install:
  - curl http://localhost/php.php
  - mysqld --version
  - apache2 -v
  - php -m
  - php -ini | grep memory_limit
  # Fix travis error https://github.com/travis-ci/travis-ci/issues/8607
  - sudo rm -vf /etc/apt/sources.list.d/*riak*
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
  # Get Chrome driver
  - wget https://chromedriver.storage.googleapis.com/2.35/chromedriver_linux64.zip && unzip chromedriver_linux64.zip
  - sudo mv chromedriver /usr/bin
  - sudo chmod +x /usr/bin/chromedriver
  - chromedriver --version

  # Get Selenium
  - wget http://selenium-release.storage.googleapis.com/3.141/selenium-server-standalone-3.141.59.jar
  # Check java
  - java -version
  - java -jar selenium-server-standalone-3.141.59.jar -log selenium.log  > /dev/null &

  # Use default config
  - sudo apt-get update
  - sudo apt-get install php php-mysql php-xml php-gd php-intl php-soap php-bcmath
  #- sudo a2enmod rewrite actions fastcgi alias

  # Apache & php-fpm configuration
  - bash tests/travis/setup-php-fpm.sh
  - bash tests/travis/setup-apache.sh

  # Starting Apache
  - sudo service apache2 restart
  - sudo cat /etc/hosts
  - curl http://localhost/php.php

install:
  - phpenv config-rm xdebug.ini || return 0
  - composer update --prefer-source --no-interaction
  # Install bundle js/css
  - php bin/console assets:install
  # Permissions
  - sudo chmod -R 777 var public
  # Dump js routes
  - php bin/console fos:js-routing:dump --format=json --target=public/js/fos_js_routes.json
  # Install third party js/css libraries
  - yarn install
  - ./node_modules/.bin/encore dev
  # Permissions
  - sudo chown -R www-data:www-data $TRAVIS_BUILD_DIR
  - sudo chown -R 775 $TRAVIS_BUILD_DIR
  - sudo chmod +x /home/travis/build
  - ls -la public/build

script:
  - cd tests/behat
  #  - travis_wait 45 ../../vendor/behat/behat/bin/behat -v
  - ../../vendor/behat/behat/bin/behat -v features/actionInstall.feature
#  - ../../vendor/behat/behat/bin/behat -v features/adminFillUsers.feature
#  - ../../vendor/behat/behat/bin/behat -v features/course.feature
#  - ../../vendor/behat/behat/bin/behat -v features/createUser.feature

after_failure:
  - sudo cat /var/log/apache2/error.log

# configure notifications (email, IRC, campfire etc)
notifications:
  slack:
    rooms:
      secure: wlaaOwNt58ENjx2PEciISr4VBRWXp6YfI8TAZgvhDO1H0XpLByRYyktgm/+h6NQWvTEcPGBSFcsIA6K0N8FA52/fdDQFxbe0en+b4q7AGNLdjTRdszfZ4AbIdRngSBFKRmXC5IX0dEx/nGWYp5fRs26QPvgBadpj8M11BnL7qhg=
