language: php

php:
  - 5.3
  - 5.4
  - 5.5

before_script: composer install -n
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq php5-imagick

script: phpunit -c tests/phpunit
