language: php

php:
  - 5.4
  - 5.5
  - 5.6

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq mysql-server
  - sudo apt-get install -qq apache2 libapache2-mod-fastcgi
  - sudo apt-get install -qq php5-imagick php5-curl php5-intl php5-json php5-fpm php5-mysql php5-cli

before_script:
  - composer self-update
  - composer install -n
  - composer -v update
  - phpenv config-add tests/travis-php-config.ini
  # enable php-fpm
  - sudo service php5-fpm stop
  - sudo cp ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf.default ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf
  - sudo a2enmod rewrite actions fastcgi alias
  - echo "cgi.fix_pathinfo = 1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - ~/.phpenv/versions/$(phpenv version-name)/sbin/php-fpm
  # configure apache virtual hosts
  - sudo cp -f tests/travis-apache /etc/apache2/sites-available/default
  - sudo sed -e "s?%TRAVIS_BUILD_DIR%?$(pwd)?g" --in-place /etc/apache2/sites-available/default
  - sudo service apache2 restart
  # install Chash, a database, and then install Chamilo
  #- git clone https://github.com/chamilo/chash
  #- cd chash
  #- composer install
  #- composer update
  #- php5 -d phar.readonly=0 createPhar.php
  #- chmod +x chash.phar
  #- sudo mv chash.phar /usr/local/bin/chash
  #- cd ..
  - git clone -b nophpversioncheck --single-branch https://github.com/ywarnier/chamilo-cli-install.git
  - cp chamilo-cli-install/chamilo-cli-installer.php main/install/
  - mysql -u root -e 'create database chamilo'
  # install Chamilo with Chash - see reference https://github.com/sonnym/travis-ci-drupal-module-example/blob/master/.travis.yml
  - sudo chmod -R 0777 archive courses home main/upload/ main/default_course_document/images main/inc/conf searchdb main/lang main/css
  - cd main/install/
  - sudo php5 chamilo-cli-installer.php -l admin -p admin -U travis -u 'http://localhost/' -X travis -L english -z 'admin@example.com' -f 'John' -g 'Doe' -b '555-5555' -c 'Test campus' -y 'Chamilo' -x 'https://chamilo.org'
  - cd ../..
  #- sudo chash chash:chamilo_install --no-interaction --sitename="Chamilo" --site_url="http://localhost/" --institution="Chamilo" --institution_url="https://chamilo.org" --encrypt_method="sha1" --firstname="John" --lastname="Doe" --language="english" --dbname="chamilo" --dbuser="root" --permissions_for_new_directories="0777" --permissions_for_new_files="0666" --username="admin" --password="admin" --email="admin@example.com" --phone="555-5555" 1.10.0 /home/travis/build/chamilo/chamilo-lms

script:
  # - phpunit -c tests/phpunit
  # pwd shows /home/travis/build/chamilo/chamilo-lms
  - cd tests && ../vendor/behat/behat/bin/behat -v

# configure notifications (email, IRC, campfire etc)
notifications:
  irc: "irc.freenode.org#chamilo"