course_url:
    path: courses
#    resource: '@ChamiloCoreBundle/Controller/Admin'

core_tool:
    resource: '@ChamiloCourseBundle/Controller'
    type: annotation
    prefix: /courses/{course}/

resources_get_info:
    path: /resources/info/{id}
    defaults:
        _controller: Chamilo\CoreBundle\Controller\ResourceController::showAction
    requirements:
        file: .+ # allow "/" in {file}

resources_list:
    path: /resources/{type}/list
    defaults:
        _controller: Chamilo\CoreBundle\Controller\ResourceController::listAction
    requirements:
        file: .+ # allow "/" in {file}

resources_get_file:
    path: /resources/file/{id}
    defaults:
        _controller: Chamilo\CoreBundle\Controller\ResourceController::getResourceFileAction
    requirements:
        file: .+ # allow "/" in {file}

resources_document_get_file:
    path: /courses/{course}/document/{file}
    defaults:
        _controller: Chamilo\CoreBundle\Controller\ResourceController::getDocumentAction
    requirements:
        file: .+ # allow "/" in {file}

chamilo_course_tool_intro_create:
    path: /courses/{course}/introduction/{tool}/create/
    methods: [GET, POST]
    defaults:
        _controller: Chamilo\CourseBundle\Controller\CToolIntroController::createAction
    requirements:
        tool: "[a-zA-Z_]+"

chamilo_course_tool_intro_update:
    path: /courses/{course}/introduction/{tool}/update/
    methods: [GET]
    defaults:
        _controller: Chamilo\CourseBundle\Controller\CToolIntroController::updateAction

chamilo_course_tool_list:
    path: /courses/{course}/introduction
    methods: [GET]
    defaults:
        _controller: Chamilo\CourseBundle\Controller\CToolIntroController::indexAction


#chamilo_course.c_tool_intro:
#    resource: |
#        alias: chamilo_course.c_tool_intro
#        path: /courses/{course}/introduction/{tool}
#        templates: :Admin/Book
#    type: sylius.resource_api

# Course settings
chamilo_course_settings:
    path: /courses/{course}/settings/{namespace}
    defaults:
        _controller: Chamilo\CourseBundle\Controller\SettingsController::updateAction
        template: ChamiloCourseBundle:Settings:default.html.twig

chamilo_course_tool_index:
    path: /courses/{course}/tools
    methods: [GET, POST, HEAD, DELETE]
    defaults:
        _controller: Chamilo\CourseBundle\Controller\CToolIntroController::indexAction
