#chamilo_course.c_tool_intro:
#    resource: |
#        alias: chamilo_course.c_tool_intro
#        path: /courses/{course}/introduction/{tool}
#        templates: :Admin/Book
#    type: sylius.resource_api

# Course settings
#chamilo_course_settings:
#    path: /course/{cid}/settings/{namespace}
#    defaults:
#        _controller: Chamilo\CourseBundle\Controller\SettingsController::updateAction
#        template: ChamiloCourseBundle:Settings:default.html.twig
