parameters:
    chamilo_course.tool_chain.class: Chamilo\CourseBundle\ToolChain
    chamilo_course.controller.settings.class: Chamilo\CourseBundle\Controller\SettingsController
    chamilo_course.settings.form_factory.class: Chamilo\CourseBundle\Form\Factory\SettingsFormFactory
    chamilo_course.settings.manager.class: Chamilo\CourseBundle\Manager\SettingsManager
    chamilo_course.settings.schema_registry.class: Sylius\Component\Registry\ServiceRegistry
    chamilo_course.entity.manager.group_manager.class: Chamilo\CourseBundle\Entity\Manager\GroupManager
    chamilo_course.entity.group: Chamilo\CourseBundle\Entity\CGroupInfo

services:
    # Managers
    chamilo_course.manager.group:
        class: '%chamilo_course.entity.manager.group_manager.class%'
        arguments: ['%chamilo_course.entity.group%', '@doctrine']

    # Event Listeners
    chamilo_course.listener.course:
        class: Chamilo\CourseBundle\EventListener\CourseListener
        arguments: ['@service_container']
        tags:
            - {name: kernel.event_listener, event: kernel.request, method: onKernelRequest}
            - {name: kernel.event_listener, event: kernel.response, method: onKernelResponse}
            - {name: kernel.event_listener, event: kernel.controller, method: onKernelController, priority: 10}

    # Sets the user access in a course listener
    chamilo_course.listener.course_access:
        class: Chamilo\CourseBundle\EventListener\CourseAccessListener
        arguments:
            - '@doctrine.orm.entity_manager'
        calls:
            - [setRequest, ['@request_stack']]
        tags:
            - {name: kernel.event_listener, event: chamilo_course.course.access, method: onCourseAccessEvent}

    # Sets the user access in a course session listener
    chamilo_course.listener.session_access:
        class: Chamilo\CourseBundle\EventListener\SessionAccessListener
        arguments:
            - '@doctrine.orm.entity_manager'
        calls:
            - [setRequest, ['@request_stack']]
        tags:
            - {name: kernel.event_listener, event: chamilo_course.course.session, method: onSessionAccessEvent}
    # Voters
    # Group voter, checks if a user has permissions to do actions
    chamilo_course.security.authorization.voter.group_voter:
        class: Chamilo\CoreBundle\Security\Authorization\Voter\GroupVoter
        arguments: [
            '@doctrine.orm.entity_manager',
            '@chamilo_core.entity.manager.course_manager',
            '@chamilo_course.manager.group',
            '@service_container'
        ]
        public: false
        tags:
            - {name: security.voter}

    # Course settings
    chamilo_course.controller.settings:
        class: "%chamilo_course.controller.settings.class%"
        calls:
            - [setContainer, ['@service_container']]

    chamilo_course.settings.form_factory:
        class: Sylius\Bundle\SettingsBundle\Form\Factory\SettingsFormFactory
        arguments:
            - '@chamilo_course.registry.settings_schema'
            - '@form.factory'

    chamilo_course.repository.parameter:
        class: Chamilo\CourseBundle\Entity\Repository\CCourseSettingRepository
        factory: ["@doctrine", getRepository]
        arguments: [Chamilo\CourseBundle\Entity\CCourseSetting]

#    chamilo_settings.repository.parameter:
#        class: Chamilo\CoreBundle\Entity\Repository\SettingsCurrentRepository
#        factory: ["@doctrine", getRepository]
#        arguments: [ Chamilo\CoreBundle\Entity\SettingsCurrent ]

    chamilo_course.registry.settings_schema:
        class: Sylius\Component\Registry\ServiceRegistry
        arguments:
            - Sylius\Bundle\SettingsBundle\Schema\SchemaInterface
            - 'Course settings'

    chamilo_course.settings.manager:
        class: '%chamilo_course.settings.manager.class%'
        arguments:
            - '@chamilo_course.registry.settings_schema'
            - '@sylius.registry.settings_resolver'
            - '@sylius.manager.settings'
            - '@sylius.factory.settings'
            - '@event_dispatcher'

    # Tool chain loads the list of tool services with the tag "chamilo_course.tool"
    # Tool chain is filled in file DependencyInjection/Compiler/ToolCompilerClass.php
    chamilo_course.tool_chain:
        class: '%chamilo_course.tool_chain.class%'

    # Agenda tool
    chamilo_course.tool.agenda:
        class: Chamilo\CourseBundle\Tool\Agenda
        arguments:
            - agenda
            - authoring
            - calendar/agenda.php
            - agenda.gif
            - chamilo_course.settings.agenda
        tags:
            - {name: chamilo_course.tool}

    # Agenda tool settings
    chamilo_course.settings.agenda:
        class: Chamilo\CourseBundle\Settings\AgendaCourseSettingsSchema
        tags:
            - {name: chamilo_course.settings_schema, alias: chamilo_course.settings.agenda, namespace: agenda}

    # Announcement tool
    chamilo_course.tool.announcement:
        class: Chamilo\CourseBundle\Tool\Announcement
        arguments:
            - announcement
            - authoring
            - announcements/announcements.php
            - valves.gif
            - chamilo_course.settings.announcement
        tags:
            - {name: chamilo_course.tool}

    # Announcement tool settings
    chamilo_course.settings.announcement:
        class: Chamilo\CourseBundle\Settings\AnnouncementCourseSettingsSchema
        tags:
            - {name: chamilo_course.settings_schema, alias: chamilo_course.settings.announcement, namespace: announcement}

    chamilo_course.tool.assignment:
        class: Chamilo\CourseBundle\Tool\Assignment
        arguments:
            - assignment
            - interaction
            - work/work.php
            - works.gif
            - chamilo_course.settings.assignment
        tags:
            - {name: chamilo_course.tool}

    # Course settings
    chamilo_course.settings.assignment:
        class: Chamilo\CourseBundle\Settings\AssignmentCourseSettingsSchema
        tags:
            - {name: chamilo_course.settings_schema, alias: chamilo_course.settings.assignment, namespace: assignment}

    chamilo_course.tool.attendance:
        class: Chamilo\CourseBundle\Tool\Attendance
        arguments:
            - attendance
            - authoring
            - attendance/index.php
            - attendance.gif
            - '@chamilo_course.settings.attendance'
        tags:
            - {name: chamilo_course.tool}

    # Course settings
    chamilo_course.settings.attendance:
        class: Chamilo\CourseBundle\Settings\AttendanceCourseSettingsSchema
        tags:
            - {name: chamilo_course.settings_schema, alias: chamilo_course.settings.attendance, namespace: attendance}

    chamilo_course.tool.blog:
        class: Chamilo\CourseBundle\Tool\Blog
        arguments:
            - blog
            - admin
            - blog/blog_admin.php
            - blog_admin.gif
            - '@chamilo_course.settings.blog'
        tags:
            - {name: chamilo_course.tool}

    # Course settings
    chamilo_course.settings.blog:
        class: Chamilo\CourseBundle\Settings\BlogCourseSettingsSchema
        tags:
            - {name: chamilo_course.settings_schema, alias: chamilo_course.settings.blog, namespace: blog}

    chamilo_course.tool.course_description:
        class: Chamilo\CourseBundle\Tool\CourseDescription
        arguments:
            - course_description
            - authoring
            - course_description/index.php
            - info.gif
            - '@chamilo_course.settings.course_description'
        tags:
            - {name: chamilo_course.tool}

    # Course settings
    chamilo_course.settings.course_description:
        class: Chamilo\CourseBundle\Settings\CourseDescriptionCourseSettingsSchema
        tags:
            - {name: chamilo_course.settings_schema, alias: chamilo_course.settings.course_description, namespace: course_description}

    chamilo_course.tool.chat:
        class: Chamilo\CourseBundle\Tool\Chat
        arguments:
            - chat
            - interaction
            - chat/chat.php
            - chat.gif
            - '@chamilo_course.settings.chat'
        tags:
            - {name: chamilo_course.tool}

    # Course settings
    chamilo_course.settings.chat:
        class: Chamilo\CourseBundle\Settings\ChatCourseSettingsSchema
        tags:
            - {name: chamilo_course.settings_schema, alias: chamilo_course.settings.chat, namespace: chat}

    chamilo_course.tool.course_progress:
        class: Chamilo\CourseBundle\Tool\CourseProgress
        arguments:
            - course_progress
            - authoring
            - course_progress/index.php
            - course_progress.gif
            - '@chamilo_course.settings.course_progress'

        tags:
            - {name: chamilo_course.tool}

    # Course settings
    chamilo_course.settings.course_progress:
        class: Chamilo\CourseBundle\Settings\CourseProgressCourseSettingsSchema
        tags:
            - {name: chamilo_course.settings_schema, alias: chamilo_course.settings.course_progress, namespace: course_progress}

    chamilo_course.tool.document:
        class: Chamilo\CourseBundle\Tool\Document
        arguments:
            - document
            - authoring
            - document/document.php
            - folder_document.gif
            - '@chamilo_course.settings.document'
        tags:
            - {name: chamilo_course.tool}

    # Course settings
    chamilo_course.settings.document:
        class: Chamilo\CourseBundle\Settings\DocumentCourseSettingsSchema
        tags:
            - {name: chamilo_course.settings_schema, alias: chamilo_course.settings.document, namespace: document}

    chamilo_course.tool.dropbox:
        class: Chamilo\CourseBundle\Tool\Dropbox
        arguments:
            - dropbox
            - interaction
            - dropbox/index.php
            - dropbox.gif
            - '@chamilo_course.settings.dropbox'

        tags:
            - {name: chamilo_course.tool}

    # Course settings
    chamilo_course.settings.dropbox:
        class: Chamilo\CourseBundle\Settings\DropboxCourseSettingsSchema
        tags:
            - {name: chamilo_course.settings_schema, alias: chamilo_course.settings.dropbox, namespace: dropbox}

    chamilo_course.tool.exercise:
        class: Chamilo\CourseBundle\Tool\Exercise
        arguments:
            - quiz
            - authoring
            - exercise/exercice.php
            - quiz.gif
            - '@chamilo_course.settings.exercise'

        tags:
            - {name: chamilo_course.tool}

    # Course settings
    chamilo_course.settings.exercise:
        class: Chamilo\CourseBundle\Settings\ExerciseCourseSettingsSchema
        tags:
            - {name: chamilo_course.settings_schema, alias: chamilo_course.settings.quiz, namespace: quiz}

    chamilo_course.tool.forum:
        class: Chamilo\CourseBundle\Tool\Forum
        arguments:
            - forum
            - interaction
            - forum/index.php
            - forum.gif
            - '@chamilo_course.settings.forum'

        tags:
            - {name: chamilo_course.tool}

    # Course settings
    chamilo_course.settings.forum:
        class: Chamilo\CourseBundle\Settings\ForumCourseSettingsSchema
        tags:
            - {name: chamilo_course.settings_schema, alias: chamilo_course.settings.forum, namespace: forum}

    chamilo_course.tool.glossary:
        class: Chamilo\CourseBundle\Tool\Glossary
        arguments:
            - glossary
            - authoring
            - glossary/index.php
            - glossary.gif
            - '@chamilo_course.settings.glossary'

        tags:
            - {name: chamilo_course.tool}

    # Course settings
    chamilo_course.settings.glossary:
        class: Chamilo\CourseBundle\Settings\GlossaryCourseSettingsSchema
        tags:
            - {name: chamilo_course.settings_schema, alias: chamilo_course.settings.glossary, namespace: glossary}

    chamilo_course.tool.gradebook:
        class: Chamilo\CourseBundle\Tool\Gradebook
        arguments:
            - gradebook
            - authoring
            - gradebook/index.php
            - gradebook.gif
            - '@chamilo_course.settings.gradebook'

        tags:
            - {name: chamilo_course.tool}

    # Course settings
    chamilo_course.settings.gradebook:
        class: Chamilo\CourseBundle\Settings\GradebookCourseSettingsSchema
        tags:
            - {name: chamilo_course.settings_schema, alias: chamilo_course.settings.gradebook, namespace: gradebook}

    chamilo_course.tool.group:
        class: Chamilo\CourseBundle\Tool\Group
        arguments:
            - group
            - interaction
            - group/group.php
            - group.gif
            - '@chamilo_course.settings.group'

        tags:
            - {name: chamilo_course.tool}

    # Course settings
    chamilo_course.settings.group:
        class: Chamilo\CourseBundle\Settings\GroupCourseSettingsSchema
        tags:
            - {name: chamilo_course.settings_schema, alias: chamilo_course.settings.group, namespace: group}

    chamilo_course.tool.learning_path:
        class: Chamilo\CourseBundle\Tool\LearningPath
        arguments:
            - learnpath
            - authoring
            - lp/lp_controller.php
            - scorms.gif
            - '@chamilo_course.settings.learning_path'
        tags:
            - {name: chamilo_course.tool}

    # Course settings
    chamilo_course.settings.learning_path:
        class: Chamilo\CourseBundle\Settings\LearningPathCourseSettingsSchema
        tags:
            - {name: chamilo_course.settings_schema, alias: chamilo_course.settings.learnpath, namespace: learnpath}

    chamilo_course.tool.link:
        class: Chamilo\CourseBundle\Tool\Link
        arguments:
            - link
            - authoring
            - link/link.php
            - links.gif
            - '@chamilo_course.settings.link'

        tags:
            - {name: chamilo_course.tool}

    # Course settings
    chamilo_course.settings.link:
        class: Chamilo\CourseBundle\Settings\LinkCourseSettingsSchema
        tags:
            - {name: chamilo_course.settings_schema, alias: chamilo_course.settings.link, namespace: link}

    chamilo_course.tool.maintenance:
        class: Chamilo\CourseBundle\Tool\Maintenance
        arguments:
            - maintenance
            - admin
            - course_info/maintenance.php
            - backup.gif
            - '@chamilo_course.settings.maintenance'
        tags:
            - {name: chamilo_course.tool}

    # Course settings
    chamilo_course.settings.maintenance:
        class: Chamilo\CourseBundle\Settings\MaintenanceCourseSettingsSchema
        tags:
            - {name: chamilo_course.settings_schema, alias: chamilo_course.settings.maintenance, namespace: maintenance}

    chamilo_course.tool.settings:
        class: Chamilo\CourseBundle\Tool\Settings
        arguments:
            - settings
            - admin
            - course_info/infocours.php
            - reference.gif
            - '@chamilo_course.settings.settings'

        tags:
            - {name: chamilo_course.tool}

    # Course settings
    chamilo_course.settings.settings:
        class: Chamilo\CourseBundle\Settings\SettingsCourseSettingsSchema
        tags:
            - {name: chamilo_course.settings_schema, alias: chamilo_course.settings.settings, namespace: settings}

    chamilo_course.tool.survey:
        class: Chamilo\CourseBundle\Tool\Survey
        arguments:
            - survey
            - interaction
            - survey/survey_list.php
            - survey.gif
            - '@chamilo_course.settings.survey'

        tags:
            - {name: chamilo_course.tool}

    # Course settings
    chamilo_course.settings.survey:
        class: Chamilo\CourseBundle\Settings\SurveyCourseSettingsSchema
        tags:
            - {name: chamilo_course.settings_schema, alias: chamilo_course.settings.survey, namespace: survey}

    chamilo_course.tool.tracking:
        class: Chamilo\CourseBundle\Tool\Tracking
        arguments:
            - tracking
            - admin
            - tracking/courseLog.php
            - statistics.gif
            - '@chamilo_course.settings.tracking'

        tags:
            - {name: chamilo_course.tool}

    # Course settings
    chamilo_course.settings.tracking:
        class: Chamilo\CourseBundle\Settings\TrackingCourseSettingsSchema
        tags:
            - {name: chamilo_course.settings_schema, alias: chamilo_course.settings.tracking, namespace: tracking}

    chamilo_course.tool.user:
        class: Chamilo\CourseBundle\Tool\User
        arguments:
            - user
            - interaction
            - user/user.php
            - members.gif
            - '@chamilo_course.settings.user'

        tags:
            - {name: chamilo_course.tool}
    # Course settings
    chamilo_course.settings.user:
        class: Chamilo\CourseBundle\Settings\UserCourseSettingsSchema
        tags:
            - {name: chamilo_course.settings_schema, alias: chamilo_course.settings.user, namespace: user}

    chamilo_course.tool.wiki:
        class: Chamilo\CourseBundle\Tool\Wiki
        arguments:
            - wiki
            - interaction
            - wiki/index.php
            - wiki.gif
            - '@chamilo_course.settings.wiki'

        tags:
            - {name: chamilo_course.tool}

    # Course settings
    chamilo_course.settings.wiki:
        class: Chamilo\CourseBundle\Settings\WikiCourseSettingsSchema
        tags:
            - {name: chamilo_course.settings_schema, alias: chamilo_course.settings.wiki, namespace: wiki}
