services:
    _defaults:
        autowire: true
        public: true

    League\Flysystem\MountManager: '@oneup_flysystem.mount_manager'

    chamilo_course.registry.settings_schema:
        class: Sylius\Component\Registry\ServiceRegistry
        arguments:
            - Sylius\Bundle\SettingsBundle\Schema\SchemaInterface
            - 'Course settings'

    Chamilo\CourseBundle\Manager\SettingsManager:
        arguments:
            - '@chamilo_course.registry.settings_schema'
            - '@doctrine.orm.entity_manager'
            - '@chamilo_course.repository.parameter'
            - '@event_dispatcher'
            - '@request_stack'

    Chamilo\CourseBundle\Manager\SettingsFormFactory:
        arguments:
            - '@chamilo_course.registry.settings_schema'
            - '@form.factory'
        public: true

    chamilo_course.repository.parameter:
        class: Chamilo\CourseBundle\Repository\CCourseSettingRepository

    Chamilo\CourseBundle\Repository\:
        resource: ../../Repository
        exclude: '../../Repository/{CDocumentRepository.php|CQuizRepository.php}'
        tags: ['doctrine.repository_service']

#    resources.asset.illustration:
#        arguments:
#            $entityName: 'Chamilo\CoreBundle\Entity\Illustration'
#            $repository: 'Chamilo\CoreBundle\Repository\IllustrationRepository'

    # Entity repository as a service
    Chamilo\CourseBundle\Repository\CAttendanceRepository:
        arguments:
            $className: 'Chamilo\CourseBundle\Entity\CAttendance'

    Chamilo\CourseBundle\Repository\CAnnouncementAttachmentRepository:
        arguments:
            $className: 'Chamilo\CourseBundle\Entity\CAnnouncementAttachment'

    Chamilo\CourseBundle\Repository\CAnnouncementRepository:
        arguments:
            $className: 'Chamilo\CourseBundle\Entity\CAnnouncement'

    Chamilo\CourseBundle\Repository\CCalendarEventRepository:
        arguments:
            $className: 'Chamilo\CourseBundle\Entity\CCalendarEvent'

    Chamilo\CourseBundle\Repository\CCalendarEventAttachmentRepository:
        arguments:
            $className: 'Chamilo\CourseBundle\Entity\CCalendarEventAttachment'

    Chamilo\CourseBundle\Repository\CChatConversationRepository:
        arguments:
            $className: 'Chamilo\CourseBundle\Entity\CChatConversation'

    Chamilo\CourseBundle\Repository\CCourseDescriptionRepository:
        arguments:
            $className: 'Chamilo\CourseBundle\Entity\CCourseDescription'

    Chamilo\CourseBundle\Repository\CDocumentRepository:
        arguments:
            $className: 'Chamilo\CourseBundle\Entity\CDocument'

    Chamilo\CourseBundle\Repository\CExerciseCategoryRepository:
        arguments:
            $className: 'Chamilo\CourseBundle\Entity\CExerciseCategory'

    Chamilo\CourseBundle\Repository\CForumAttachmentRepository:
        arguments:
            $className: 'Chamilo\CourseBundle\Entity\CForumAttachment'

    Chamilo\CourseBundle\Repository\CForumForumRepository:
        arguments:
            $className: 'Chamilo\CourseBundle\Entity\CForumForum'

    Chamilo\CourseBundle\Repository\CForumCategoryRepository:
        arguments:
            $className: 'Chamilo\CourseBundle\Entity\CForumCategory'

    Chamilo\CourseBundle\Repository\CForumPostRepository:
        arguments:
            $className: 'Chamilo\CourseBundle\Entity\CForumPost'

    Chamilo\CourseBundle\Repository\CForumThreadRepository:
        arguments:
            $className: 'Chamilo\CourseBundle\Entity\CForumThread'

    Chamilo\CourseBundle\Repository\CGlossaryRepository:
        arguments:
            $className: 'Chamilo\CourseBundle\Entity\CGlossary'

    Chamilo\CourseBundle\Repository\CGroupInfoRepository:
        arguments:
            $className: 'Chamilo\CourseBundle\Entity\CGroupInfo'

    Chamilo\CourseBundle\Repository\CQuizRepository:
        arguments:
            $className: 'Chamilo\CourseBundle\Entity\CQuiz'

    Chamilo\CourseBundle\Repository\CQuizQuestionCategoryRepository:
        arguments:
            $className: 'Chamilo\CourseBundle\Entity\CQuizQuestionCategory'

    Chamilo\CourseBundle\Repository\CQuizQuestionRepository:
        arguments:
            $className: 'Chamilo\CourseBundle\Entity\CQuizQuestion'

    Chamilo\CourseBundle\Repository\CLinkRepository:
        arguments:
            $className: 'Chamilo\CourseBundle\Entity\CLink'

    Chamilo\CourseBundle\Repository\CLinkCategoryRepository:
        arguments:
            $className: 'Chamilo\CourseBundle\Entity\CLinkCategory'

    Chamilo\CourseBundle\Repository\CLpRepository:
        arguments:
            $className: 'Chamilo\CourseBundle\Entity\CLp'

    Chamilo\CourseBundle\Repository\CLpCategoryRepository:
        arguments:
            $className: 'Chamilo\CourseBundle\Entity\CLpCategory'

    Chamilo\CourseBundle\Repository\CStudentPublicationRepository:
        arguments:
            $className: 'Chamilo\CourseBundle\Entity\CStudentPublication'

    Chamilo\CourseBundle\Repository\CStudentPublicationAssignmentRepository:
        arguments:
            $className: 'Chamilo\CourseBundle\Entity\CStudentPublicationAssignment'

    Chamilo\CourseBundle\Repository\CStudentPublicationCommentRepository:
        arguments:
            $className: 'Chamilo\CourseBundle\Entity\CStudentPublicationComment'

    Chamilo\CourseBundle\Repository\CThematicRepository:
        arguments:
            $className: 'Chamilo\CourseBundle\Entity\CThematic'

    Chamilo\CourseBundle\Repository\CThematicAdvanceRepository:
        arguments:
            $className: 'Chamilo\CourseBundle\Entity\CThematicAdvance'

    Chamilo\CourseBundle\Repository\CThematicPlanRepository:
        arguments:
            $className: 'Chamilo\CourseBundle\Entity\CThematicPlan'

    Chamilo\CourseBundle\Repository\CShortcutRepository:
        arguments:
            $className: 'Chamilo\CourseBundle\Entity\CShortcut'

    Chamilo\CourseBundle\Repository\CToolRepository:
        arguments:
            $className: 'Chamilo\CourseBundle\Entity\CTool'

    # Event Listeners
    chamilo_course.listener.course:
        class: Chamilo\CourseBundle\EventListener\CourseListener
        calls:
            - [setContainer, ['@service_container']]
        tags:
            - {name: kernel.event_listener, event: kernel.request, method: onKernelRequest, priority: 6}
            - {name: kernel.event_listener, event: kernel.response, method: onKernelResponse}
            - {name: kernel.event_listener, event: kernel.controller, method: onKernelController}

    # Sets the user access in a course listener
    chamilo_course.listener.course_access:
        class: Chamilo\CourseBundle\EventListener\CourseAccessListener
        arguments:
            - '@doctrine.orm.entity_manager'
        calls:
            - [setRequest, ['@request_stack']]
        tags:
            - {name: kernel.event_listener, event: chamilo_course.course.access, method: onCourseAccessEvent}

    # Sets the user access in a course session listener
    chamilo_course.listener.session_access:
        class: Chamilo\CourseBundle\EventListener\SessionAccessListener
        arguments:
            - '@doctrine.orm.entity_manager'
        calls:
            - [setRequest, ['@request_stack']]
        tags:
            - {name: kernel.event_listener, event: chamilo_course.course.session, method: onSessionAccessEvent}
    # Voters
    # Group voter, checks if a user has permissions to do actions
    chamilo_course.security.authorization.voter.group_voter:
        class: Chamilo\CoreBundle\Security\Authorization\Voter\GroupVoter
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@Chamilo\CoreBundle\Repository\CourseRepository'
            - '@Chamilo\CourseBundle\Repository\CGroupInfoRepository'
            - '@security.authorization_checker'
            - '@service_container'
        public: false
        tags:
            - {name: security.voter}
