services:
    _defaults:
        autowire: true
        public: true

    chamilo_course.registry.settings_schema:
        class: Sylius\Bundle\SettingsBundle\Registry\ServiceRegistry
        arguments:
            - 'Sylius\Bundle\SettingsBundle\Schema\SchemaInterface'
            - 'Course settings schema'

    Chamilo\CourseBundle\Settings\SettingsCourseManager:
        arguments:
            - '@chamilo_course.registry.settings_schema'
            - '@doctrine.orm.entity_manager'
            - '@Chamilo\CourseBundle\Repository\CCourseSettingRepository'
            - '@event_dispatcher'
            - '@request_stack'

    Chamilo\CourseBundle\Settings\SettingsFormFactory:
        arguments:
            - '@chamilo_course.registry.settings_schema'
            - '@form.factory'
        public: true

    Chamilo\CourseBundle\Repository\CCourseSettingRepository: ~

    Chamilo\CourseBundle\Repository\:
        resource: '../../Repository/'
        tags: ['doctrine.repository_service']
        calls:
            - setAuthorizationChecker: ['@security.authorization_checker']
            - setRouter: ['@router']
            - setSlugify: ['@cocur_slugify']
            - setToolChain: ['@Chamilo\CoreBundle\Tool\ToolChain']
            - setResourceNodeRepository: ['@Chamilo\CoreBundle\Repository\ResourceNodeRepository']
            - setRequestStack: ['@request_stack']
        exclude: '../../Repository/CCourseSettingRepository.php'
