#chamilo_lms_notebook:
#    resource: "@ChamiloNotebookBundle/Controller/"
#    type:     annotation
#    prefix:   /notebook
chamilo_notebook_new:
    pattern: courses/{course}/notebook/new
    methods: [GET, POST]
    defaults:
        _controller: chamilo.controller.notebook:createAction
        _sylius:
            factory:
                method: createNewWithCourse
                arguments: [$course]

chamilo_notebook_show:
    pattern: courses/{course}/notebook/{id}
    methods: [GET]
    requirements:
            id:  \d+
    defaults:
        _controller: chamilo.controller.notebook:showAction
        _sylius:
            criteria: { id: $id }

chamilo_notebook_index:
    pattern: courses/{course}/notebook
    methods: [GET]
    defaults:
        _controller: chamilo.controller.notebook:indexAction

chamilo_notebook_settings:
    pattern: courses/{course}/notebook/settings
    defaults:
        _controller: sylius.controller.settings:updateAction
        namespace: notebook
        template: ChamiloCoreBundle:Settings:default.html.twig

