services:
    # Tool definition
    chamilo_notebook.tool.notebook:
        class: Chamilo\NotebookBundle\Tool\Notebook
        arguments:
            - notebook
            - interaction
            - notebook/index.php
            - notebook.gif
            - @chamilo_notebook.settings.notebook_course_settings_schema
            - @chamilo_notebook.entity.notebook_manager

        tags:
            - { name: chamilo_course.tool }

    # Form (add/edit)
    chamilo_notebook_notebook:
        class: Chamilo\NotebookBundle\Form\Type\NotebookType
        tags:
           -  { name: form.type }

    # Database manager
    chamilo_notebook.entity.notebook_manager:
        class: Chamilo\NotebookBundle\Entity\NotebookManager
        arguments:
            - Chamilo\NotebookBundle\Entity\CNotebook
            - @doctrine

    # Global course settings
    chamilo_notebook.settings.notebook_settings_schema:
        class: Chamilo\NotebookBundle\Settings\NotebookSettingsSchema
        tags:
            - { name: sylius.settings_schema, namespace: notebook }

    # Local course settings
    chamilo_notebook.settings.notebook_course_settings_schema:
        class: Chamilo\NotebookBundle\Settings\NotebookCourseSettingsSchema
        tags:
            - { name: chamilo_course.settings_schema, namespace: notebook }
