services:
    # Icon in course home
    chamilo_notebook.tool.notebook.class:
        class: Chamilo\NotebookBundle\Tool\Notebook
        arguments:
            - notebook
            - interaction
            - notebook/index.php
            - notebook.gif
            - @chamilo_notebook.course_settings_schema.notebook

        tags:
            - { name: chamilo_course.tool }

    # Form (add/edit)
    chamilo_notebook.form.type:
        class: Chamilo\NotebookBundle\Form\Type\CNotebookType
        tags:
           -  { name: form.type }

    # Database manager
    chamilo_notebook.notebook_manager:
        class: Chamilo\NotebookBundle\Entity\CNotebookManager

    # Global settings for the tool (admin)
    chamilo_notebook.settings_schema.notebook:
        class: Chamilo\NotebookBundle\Settings\NotebookSettingsSchema
        tags:
            - { name: sylius.settings_schema, namespace: notebook }

    # Course settings (teacher)
    chamilo_notebook.course_settings_schema.notebook:
        class: Chamilo\NotebookBundle\Settings\NotebookCourseSettingsSchema
        tags:
            - { name: chamilo_course.settings_schema, namespace: notebook }
