services:
    # Icon in course home
    chamilo.notebookbundle.tool.notebook.class:
        class: Chamilo\NotebookBundle\Tool\Notebook
        arguments:
            - notebook
            - interaction
            - notebook/index.php
            - notebook.gif

        tags:
            - { name: chamilo.course.tool }

    # Form (add/edit)
    chamilo_notebook:
        class: Chamilo\NotebookBundle\Form\Type\CNotebookType
        tags:
           -  { name: form.type }

    # Database manager
    notebook.manager:
        class: Chamilo\NotebookBundle\Entity\CNotebookManager

    # Admin settings for the tool
    notebook.settings_schema.notebook:
        class: Chamilo\NotebookBundle\Settings\NotebookSettingsSchema
        tags:
            - { name: sylius.settings_schema, namespace: notebook }

