services:
    chamilo.coursebundle.tool.notebook.class:
        class: Chamilo\CourseBundle\Tool\Notebook
        arguments:
            - notebook
            - interaction
            - notebook/index.php
            - notebook.gif

        tags:
            - { name: chamilo.course.tool }

    chamilo_notebook:
        class: Chamilo\NotebookBundle\Form\Type\CNotebookType
        tags:
           -  { name: form.type }

    notebook.manager:
        class: Chamilo\NotebookBundle\Entity\CNotebookManager

    notebook.settings_schema.notebook:
        class: Chamilo\NotebookBundle\Settings\NotebookSettingsSchema
        tags:
            - { name: sylius.settings_schema, namespace: notebook }

