services:
#    chamilo.controller.notebook_configuration:
#        class: Sylius\Bundle\ResourceBundle\Controller\Configuration
#        factory_service: sylius.controller.configuration_factory
#        factory_method: createConfiguration
#        arguments:
#            - "chamilo"
#            - "notebook"
#            - "ChamiloNotebookBundle:Notebook"
#
#    chamilo.controller.notebook:
#        class: Chamilo\NotebookBundle\Controller\CNotebookController
#        arguments:
#            - @chamilo.controller.notebook_configuration
#        calls:
#            - [ setContainer,[ @service_container ] ]

    # Tool settings
    chamilo_notebook.tool.notebook.class:
        class: Chamilo\NotebookBundle\Tool\Notebook
        arguments:
            - notebook
            - interaction
            - notebook/index.php
            - notebook.gif
            - @chamilo_notebook.course_settings_schema.notebook
            - @chamilo_notebook.notebook_manager

        tags:
            - { name: chamilo_course.tool }

    # Form (add/edit)
    chamilo_notebook:
        class: Chamilo\NotebookBundle\Form\Type\CNotebookType
        tags:
           -  { name: form.type }

    # Database manager
    chamilo_notebook.notebook_manager:
        class: Chamilo\NotebookBundle\Entity\CNotebookManager
        arguments:
            - Chamilo\NotebookBundle\Entity\CNotebook
            - @doctrine

    # Global settings
    chamilo_notebook.settings_schema.notebook:
        class: Chamilo\NotebookBundle\Settings\NotebookSettingsSchema
        tags:
            - { name: sylius.settings_schema, namespace: notebook }

    # Local settings
    chamilo_notebook.course_settings_schema.notebook:
        class: Chamilo\NotebookBundle\Settings\NotebookCourseSettingsSchema
        tags:
            - { name: chamilo_course.settings_schema, namespace: notebook }
