imports:
    - { resource: config.yml }

framework:
    router:   { resource: "%kernel.root_dir%/config/routing_dev.yml" }
    profiler: { only_exceptions: false }

web_profiler:
    toolbar:             true
    intercept_redirects: false
    position: bottom
    excluded_ajax_paths:  ^/bundles|^/_wdt

monolog:
    handlers:
        main:
            type:   stream
            path:  %kernel.logs_dir%/%kernel.name%_%kernel.environment%.log
            level:  debug
#        doctrine:
#            action_level: debug
#            type:  stream
#            path:  %kernel.logs_dir%/%kernel.environment%_doctrine.log
#            channels: doctrine
#        console:
#            type:   console
#            bubble: false
        # uncomment to get logging in your browser
        # you may have to allow bigger header sizes in your Web server configuration
        #firephp:
        #    type:   firephp
        #    level:  info
        #chromephp:
        #    type:   chromephp
        #    level:  info

assetic:
    use_controller: false

#swiftmailer:
#    delivery_address: me@example.com


web_profiler_extra:
    routing:
        enabled:        true
        display_in_wdt: true
    container:
        enabled:        true
        display_in_wdt: true
    assetic:
        enabled:        true
        display_in_wdt: true
    twig:
        enabled:        true
        display_in_wdt: true

jns_xhprof:
    location_web: http://localhost/xhprof/xhprof_html
    enabled: false
