imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: assetic.yml }

    - { resource: @ChamiloCoreBundle/Resources/config/admin.yml }
    - { resource: @ChamiloNotebookBundle/Resources/config/admin.yml }

    # Mopa Bootstrap
    - { resource: mopa/mopa_bootstrap.yml }

    # Knp Paginator
    - { resource: knp/knp_paginator.yml }

    # FriendOfSymfony Bundles
    #- { resource: fos/fos_comment.yml }
    - { resource: fos/fos_rest.yml }
    - { resource: fos/fos_user.yml }
    #- { resource: fos/fos_elastica.yml }
    - { resource: fos/fos_message.yml }

    # Sonata Core Bundles
    - { resource: sonata/sonata_block.yml }
    - { resource: sonata/sonata_formatter.yml }
    - { resource: sonata/sonata_cache.yml }
    #- { resource: sonata/sonata_seo.yml }
    - { resource: sonata/sonata_timeline.yml }
    - { resource: sonata/sonata_intl.yml }
    - { resource: sonata/sonata_core.yml }

    # Sonata Feature Bundles
    - { resource: sonata/sonata_admin.yml }
    - { resource: sonata/sonata_page.yml }
    - { resource: sonata/sonata_media.yml }
    - { resource: sonata/sonata_news.yml }
    - { resource: sonata/sonata_user.yml }
    - { resource: sonata/sonata_notification.yml }
    - { resource: sonata/sonata_classification.yml }

framework:
    #esi:             ~
    translator:      { fallback: "%locale%" }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        form:
            resources:
                - 'ChamiloCoreBundle:Form'
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
        cookie_lifetime: 1440
        gc_probability: 0
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

    base_template_class: Sonata\CacheBundle\Twig\TwigTemplate14

    form:
        resources:
            - 'SonataFormatterBundle:Form:formatter.html.twig'
            - 'SonataMediaBundle:Form:media_widgets.html.twig'
            - 'SonataCoreBundle:Form:datepicker.html.twig'
            - 'ChamiloCoreBundle:Form:fields.html.twig'

    exception_controller: 'FOS\RestBundle\Controller\ExceptionController::showAction'

    paths:
      "%kernel.root_dir%/../src/Chamilo/CoreBundle/Resources/views/default": template_style

    globals:
      show_toolbar: true
      show_footer: true
      software_name:
      version:

      session_teachers: 1
      teachers: 1
      news_counter:
      news_list:
      messages_count:
      message_link:
      is_profile_editable:
      administrator_name:
      plugin_footer_left:
      plugin_footer_center:
      plugin_content_bottom:
      plugin_header_left:
      plugin_header_center:
      plugin_header_right:
      plugin_header_main:
      plugin_menu_bottom:
      plugin_menu_top:
      plugin_content_top:
      plugin_footer_right:
      footer_extra_content:
      course_session_block:
      show_course_shortcut:
      show_course_navigation_menu:
      actions:
      header:
      message:
      welcome_to_course_block:

# Assetic Configuration
#assetic:
#    debug:          "%kernel.debug%"
#    use_controller: false
#    bundles:        [ ChamiloCoreBundle, ChamiloInstallerBundle ]
#    #java: /usr/bin/java
#    filters:
#        cssrewrite: ~
#        #closure:
#        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
#        #yui_css:
#        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"
#
#        lessphp:
#          file: %kernel.root_dir%/../vendor/oyejorge/less.php/lessc.inc.php
#          apply_to: "\.less$"
#        cssrewrite: ~

#braincrafted_bootstrap:
  #less_filter: lessphp

# Doctrine Configuration
doctrine:
    dbal:
        default_connection: default

        connections:
            default:
                driver:   "%database_driver%"
                host:     "%database_host%"
                port:     "%database_port%"
                dbname:   "%database_name%"
                user:     "%database_user%"
                password: "%database_password%"
                charset:  UTF8
        types:
            json: Sonata\Doctrine\Types\JsonType
            #currency: Sonata\Component\Currency\CurrencyDoctrineType

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        default_entity_manager: default
        # auto_mapping: true
        entity_managers:
            default:
                auto_mapping: true
                mappings: ~

        #metadata_cache_driver: apc  # default "array" "apc", "memcache", "memcached", "xcache"
        #query_cache_driver: apc

# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%

jms_security_extra:
    secure_all_services: false

jms_serializer:
    metadata:
        directories:
            - { path: %kernel.root_dir%/../vendor/sonata-project/user-bundle/Resources/config/serializer/FOSUserBundle, namespace_prefix: 'FOS\UserBundle' }
            #- { path: %kernel.root_dir%/../vendor/sonata-project/ecommerce/src/BasketBundle/Resources/config/serializer/Component, namespace_prefix: 'Sonata\Component\Basket' }
            - { path: %kernel.root_dir%/../vendor/sonata-project/datagrid-bundle/Resources/config/serializer, namespace_prefix: 'Sonata\DatagridBundle' }

knp_menu:
    twig:  # use "twig: false" to disable the Twig extension and the TwigRenderer
        template: knp_menu.html.twig
    templating: false # if true, enables the helper for PHP templates
    default_renderer: twig # The renderer to use, list is also available by default

# %kernel.root_dir%/DoctrineMigrations
doctrine_migrations:
    dir_name: %kernel.root_dir%/../vendor/chamilo/chash/src/Chash/Migrations
    namespace: Chash\Migrations
    table_name: chamilo_migration_versions
    name: Chamilo Migrations

#fos_advanced_encoder:
#    encoders:
#        FOS\UserBundle\Model\UserInterface: sha512
#        legacy_encoder:
#            id: chamilo_core.encoder

sonata_admin:
    title:      Chamilo
    title_logo: apple-touch-icon.png

nelmio_api_doc: ~

sensio_framework_extra:
    view:    { annotations: false }
    router:  { annotations: true }
    request: { converters:  true }

# Doctrine extensions configuration
stof_doctrine_extensions:
    default_locale: "%locale%"
    translation_fallback: true
    orm:
        default:
            tree: true
            timestampable: true
            sluggable: true

sylius_resource:
    resources:
        chamilo.notebook:
            driver: doctrine/orm
            templates: ChamiloNotebookBundle:Notebook
            classes:
                model: Chamilo\NotebookBundle\Entity\CNotebook
                repository: Chamilo\NotebookBundle\Entity\CNotebookRepository
                controller: Chamilo\NotebookBundle\Controller\CNotebookController

# Platform settings
sylius_settings:
    driver: doctrine/orm
    classes:
        parameter:
            model: Chamilo\CoreBundle\Entity\SettingsCurrent
            repository: Chamilo\CoreBundle\Entity\Repository\SettingsCurrentRepository

# Course settings
chamilo_course:
    driver: doctrine/orm
    classes:
        parameter:
            model: Chamilo\CourseBundle\Entity\CCourseSetting
            repository: Chamilo\CourseBundle\Entity\Repository\CCourseSettingRepository

doctrine_cache:
    providers:
        sylius_settings:
            type: file_system
        chamilo_settings:
            type: file_system

# Bower configuration
sp_bower:
    assetic: true
    install_on_warmup: true
    bundles:
        ChamiloAdminThemeBundle: ~

# Run to update js dependencies: app/console sp:bower:install

# Grid default template
apy_data_grid:
    theme: ChamiloCoreBundle::grid.html.twig

liip_theme:
    themes: ['web', 'tablet', 'phone']
    active_theme: 'web'

#vich_uploader:
#    db_driver: orm # or mongodb or propel or phpcr
#
#    mappings:
#        user_image:
#            uri_prefix:         /user/images
#            upload_destination: %kernel.root_dir%/../web/uploads/user
#            inject_on_load:     false
#            delete_on_update:   true
#            delete_on_remove:   true
#            directory_namer:    chamilo_core.directory_namer.user_image
