#chamilo_theme:
#    resource: "@ChamiloThemeBundle/Controller/"
#    type:     annotation
#    prefix:   /

chamilo_course:
    resource: "@ChamiloCourseBundle/Resources/config/routing.yml"
    prefix:   /

_courses:
    resource: routing_courses.yml

_front:
    resource: routing_front.yml

_admin:
    resource: routing_admin.yml
    prefix:   /administration

_api:
    resource: routing_api.yml
    prefix:   /api

fos_message:
    resource: "@FOSMessageBundle/Resources/config/routing.xml"
    prefix: /messages

fos_comment_api:
    type: rest
    resource: "@FOSCommentBundle/Resources/config/routing.yml"
    prefix: /api
    defaults: { _format: html }

chamilo_admin_all_notifications:
    path: /notifications/
chamilo_admin_show_notification:
    path: /notifications/{notifyid}/
chamilo_admin_all_tasks:
    path: /tasks/
chamilo_admin_show_task:
    path: /tasks/{taskid}

liip_theme:
    resource: "@LiipThemeBundle/Resources/config/routing.xml"
    prefix: /theme

home:
    path: /

logout:
    path: /logout

login_check:
    path: /administration/login_check

chamilo_installer:
    resource: "@ChamiloInstallerBundle/Resources/config/routing.yml"

thrace_data_grid:
    resource: "@ThraceDataGridBundle/Resources/config/routing.xml"
    prefix:   /

# Always at the end
core_bundle:
    resource: "@ChamiloCoreBundle/Resources/config/routing.yml"

