chamilo_lms_course:
    resource: "@ChamiloLMSCourseBundle/Resources/config/routing.yml"
    prefix:   /

_courses:
    resource: routing_courses.yml

_front:
    resource: routing_front.yml

_admin:
    resource: routing_admin.yml
    prefix:   /administration

_api:
    resource: routing_api.yml
    prefix:   /api

fos_message:
    resource: "@FOSMessageBundle/Resources/config/routing.xml"
    prefix: /messages

fos_comment_api:
    type: rest
    resource: "@FOSCommentBundle/Resources/config/routing.yml"
    prefix: /api
    defaults: { _format: html }

avanzu_admin_profile:
    path: /profile

avanzu_admin_all_messages:
    path: /messages/
avanzu_admin_show_message:
    path: /messages/{messageid}
avanzu_admin_all_notifications:
    path: /notifications/
avanzu_admin_show_notification:
    path: /notifications/{notifyid}/
avanzu_admin_all_tasks:
    path: /tasks/
avanzu_admin_show_task:
    path: /tasks/{taskid}
avanzu_admin_logout:
    path: /logout

home:
    path: /

logout:
    path: /logout

login_check:
    path: /administration/login_check

chamilolms_installer:
    resource: "@ChamiloLMSInstallerBundle/Resources/config/routing.yml"

chamilolms_corebundle_platform_settings:
    pattern: /settings/platform
    defaults:
        _controller: sylius.controller.settings:updateAction
        namespace: platform
        template: ChamiloLMSCoreBundle:Settings:platform.html.twig

chamilolms_corebundle_course_settings:
    pattern: /settings/course
    defaults:
        _controller: sylius.controller.settings:updateAction
        namespace: course
        template: ChamiloLMSCoreBundle:Settings:platform.html.twig


# Always at the end
core_bundle:
    resource: "@ChamiloLMSCoreBundle/Resources/config/routing.yml"

