chamilo_lms_course:
    resource: "@ChamiloLMSCourseBundle/Resources/config/routing.yml"
    prefix:   /

_front:
    resource: routing_front.yml

_admin:
    resource: routing_admin.yml
    prefix:   /admin

_api:
    resource: routing_api.yml
    prefix:   /api

core_bundle:
    resource: "@ChamiloLMSCoreBundle/Resources/config/routing.yml"

root:
    path: /

logout:
    path: /logout
