
home:
    path: /
index:
    path: /

oro_distribution_security_logout:
    path: /logout

admin_dashboard:
    pattern: /{_locale}/administration/
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: sonata_admin_dashboard
        permanent: true # this for 301

admin_without_locale:
    pattern: /administration
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: sonata_admin_dashboard
        permanent: true # this for 301

admin_dashboard_without_locale:
    pattern: /administration/dashboard
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: sonata_admin_dashboard
        permanent: true

admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /{_locale}/administration

#hwi_oauth_redirect:
#    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
#    prefix:   /connect
#
#hwi_oauth_login:
#    resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
#    prefix:   /login

logout:
    path: /logout

sonata_user_admin_security_logout:
  path: /logout

#chamilo_course:
#    resource: "@ChamiloCourseBundle/Resources/config/routing.yml"
#    prefix:   /

#_courses:
#    resource: routing_courses.yml
#
#_front:
#    resource: routing_front.yml

_admin:
    resource: routing_admin.yml
    prefix:   /

#_api:
#    resource: routing_api.yml
#    prefix:   /api

elfinder:
     resource: "@FMElfinderBundle/Resources/config/routing.yml"

#chamilo_installer:
#    resource: "@ChamiloInstallerBundle/Resources/config/routing.yml"

# Always at the end
core_bundle:
    resource: "@ChamiloCoreBundle/Resources/config/routing.yml"

#liip_theme:
#    resource: "@LiipThemeBundle/Resources/config/routing.xml"
#    prefix: /theme

# app/config/routing.yml
fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

