security:
    encoders:
        ChamiloLMS\CoreBundle\Entity\User:
          algorithm: %password_encryption%
          encode_as_base64: false
          iterations: 1

    role_hierarchy:
        ROLE_GLOBAL_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

        ROLE_ADMIN: [ROLE_USER, ROLE_QUESTION_MANAGER, ROLE_SESSION_MANAGER, ROLE_TEACHER, ROLE_DIRECTOR, ROLE_JURY_PRESIDENT]
        ROLE_RRHH: [ROLE_TEACHER]
        ROLE_TEACHER: [ROLE_STUDENT]
        ROLE_QUESTION_MANAGER: [ROLE_STUDENT, ROLE_QUESTION_MANAGER]
        ROLE_SESSION_MANAGER: [ROLE_STUDENT, ROLE_SESSION_MANAGER, ROLE_ALLOWED_TO_SWITCH]
        ROLE_STUDENT: [ROLE_STUDENT]
        ROLE_ANONYMOUS: [ROLE_ANONYMOUS]

        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        users_db:
            entity: { class: ChamiloLMSCoreBundle:User, property: username }
    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        secured:
            pattern:    ^/
            form_login:
                login_path: login
                check_path: login_check
                success_handler: listener.login_success_handler
            logout:
                path:   /secured/logout
                target: /
                success_handler: listener.logout_success_handler
            anonymous: ~

            provider: users_db
            #http_basic:
            #    realm: "Secured Demo Area"

    access_control:
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
