#chamilo_lms_notebook:
#    resource: "@ChamiloLMSNotebookBundle/Controller/"
#    type:     annotation
#    prefix:   /notebook
chamilo_lms_notebook_new:
    pattern: /notebook/new
    methods: [GET, POST]
    defaults:
        _controller: chamilolms.controller.notebook:createAction

chamilolms_notebook_show:
    pattern: /notebook/{iid}
    methods: [GET]
    requirements:
            iid:  \d+
    defaults:
        _controller: chamilolms.controller.notebook:showAction
        _sylius:
            criteria: { iid: $iid }

chamilolms_notebook_index:
    pattern: /notebook
    methods: [GET]
    defaults:
        _controller: chamilolms.controller.notebook:indexAction

chamilolms_notebook_settings:
    pattern: /settings/notebook
    defaults:
        _controller: sylius.controller.settings:updateAction
        namespace: notebook
        template: ChamiloLMSCoreBundle:Settings:default.html.twig

