services:
    chamilolms.coursebundle.tool.notebook.class:
        class: ChamiloLMS\CourseBundle\Tool\Notebook
        arguments:
            - notebook
        tags:
            - { name: chamilolm.course.tool }
