services:
    chamilolms.coursebundle.tool.notebook.class:
        class: ChamiloLMS\CourseBundle\Tool\Notebook
        arguments:
            - notebook
        tags:
            - { name: chamilolm.course.tool }

    chamilolms_notebook:
      class: ChamiloLMS\NotebookBundle\Form\Type\CNotebookType
      tags:
         -  { name: form.type }

    notebook.manager:
        class: ChamiloLMS\NotebookBundle\Entity\CNotebookManager

    notebook.settings_schema.notebook:
        class: ChamiloLMS\NotebookBundle\Settings\NotebookSettingsSchema
        tags:
            - { name: sylius.settings_schema, namespace: notebook }

