chamilo_installer_flow:
    pattern: /installer
    defaults: { _controller: sylius.controller.process:startAction, scenarioAlias: 'chamilo_installer' }

chamilo_flow_bundle:
    resource: @SyliusFlowBundle/Resources/config/routing.yml
    prefix: /installer
