chamilo_course_notebook_settings:
    pattern: /course_settings/notebook
    defaults:
        _controller: chamilo_course.controller.settings:updateAction
        namespace: notebook
        template: ChamiloCourseBundle:Settings:default.html.twig

