parameters:
    tool_chain.class: Chamilo\CourseBundle\ToolChain

    chamilo_course.controller.settings.class: Chamilo\CourseBundle\Controller\SettingsController
    chamilo_course.settings.form_factory.class: Sylius\Bundle\SettingsBundle\Form\Factory\SettingsFormFactory
    chamilo_course.settings.manager.class: Chamilo\CourseBundle\Manager\SettingsManager
    chamilo_course.settings.schema_registry.class: Sylius\Bundle\SettingsBundle\Schema\SchemaRegistry

services:
    chamilo_course.controller.settings:
        class: "%chamilo_course.controller.settings.class%"
        calls:
          - [setContainer, [@service_container]]

    chamilo_course.settings.schema_registry:
        class: %chamilo_course.settings.schema_registry.class%

    chamilo_course.settings.form_factory:
        class: %chamilo_course.settings.form_factory.class%
        arguments:
            - @chamilo_course.settings.schema_registry
            - @form.factory

    chamilo_course.settings.cache:
        alias: doctrine_cache.providers.chamilo_settings

    chamilo_course.settings.manager:
        class: %chamilo_course.settings.manager.class%
        arguments:
            - @chamilo_course.settings.schema_registry
            - @doctrine.orm.default_entity_manager
            - @sylius.repository.parameter
            - @doctrine_cache.providers.chamilo_settings
            - @validator

    chamilo_course.tool_chain:
        class: %tool_chain.class%

    chamilo_course.tool.agenda.class:
        class: Chamilo\CourseBundle\Tool\Agenda
        arguments:
            - calendar_event
            - authoring
            - calendar/agenda.php
            - agenda.gif
        tags:
            - { name: chamilo_course.tool }

    chamilo_course.tool.announcements.class:
        class: Chamilo\CourseBundle\Tool\Announcement
        arguments:
            - announcement
            - authoring
            - announcements/announcements.php
            - valves.gif
        tags:
            - { name: chamilo_course.tool }

    chamilo_course.tool.assignment.class:
        class: Chamilo\CourseBundle\Tool\Assignment
        arguments:
            - assignment
            - interaction
            - work/work.php
            - works.gif
        tags:
            - { name: chamilo_course.tool }

    chamilo_course.tool.attendance.class:
        class: Chamilo\CourseBundle\Tool\Attendance
        arguments:
            - attendance
            - authoring
            - attendance/index.php
            - attendance.gif
        tags:
            - { name: chamilo_course.tool }

    chamilo_course.tool.blog.class:
        class: Chamilo\CourseBundle\Tool\Blog
        arguments:
            - blog_management
            - admin
            - blog/blog_admin.php
            - blog_admin.gif
        tags:
            - { name: chamilo_course.tool }

    chamilo_course.tool.course_description.class:
        class: Chamilo\CourseBundle\Tool\CourseDescription
        arguments:
            - course_description
            - authoring
            - course_description/index.php
            - info.gif
        tags:
            - { name: chamilo_course.tool }

    chamilo_course.tool.chat.class:
        class: Chamilo\CourseBundle\Tool\Chat
        arguments:
            - chat
            - interaction
            - chat/chat.php
            - chat.gif
        tags:
            - { name: chamilo_course.tool }

    chamilo_course.tool.course_progress.class:
        class: Chamilo\CourseBundle\Tool\CourseProgress
        arguments:
            - course_progress
            - authoring
            - course_progress/index.php
            - course_progress.gif

        tags:
            - { name: chamilo_course.tool }

    chamilo_course.tool.document.class:
        class: Chamilo\CourseBundle\Tool\Document
        arguments:
            - document
            - authoring
            - document/document.php
            - folder_document.gif
        tags:
            - { name: chamilo_course.tool }

    chamilo_course.tool.dropbox.class:
        class: Chamilo\CourseBundle\Tool\Dropbox
        arguments:
            - dropbox
            - interaction
            - dropbox/index.php
            - dropbox.gif

        tags:
            - { name: chamilo_course.tool }

    chamilo_course.tool.exercise.class:
        class: Chamilo\CourseBundle\Tool\Exercise
        arguments:
            - quiz
            - authoring
            - exercice/exercice.php
            - quiz.gif

        tags:
            - { name: chamilo_course.tool }

    chamilo_course.tool.forum.class:
        class: Chamilo\CourseBundle\Tool\Forum
        arguments:
            - forum
            - interaction
            - forum/index.php
            - forum.gif

        tags:
            - { name: chamilo_course.tool }

    chamilo_course.tool.glossary.class:
        class: Chamilo\CourseBundle\Tool\Glossary
        arguments:
            - glossary
            - authoring
            - glossary/index.php
            - glossary.gif

        tags:
            - { name: chamilo_course.tool }

    chamilo_course.tool.gradebook.class:
        class: Chamilo\CourseBundle\Tool\Gradebook
        arguments:
            - gradebook
            - authoring
            - gradebook/index.php
            - gradebook.gif

        tags:
            - { name: chamilo_course.tool }

    chamilo_course.tool.group.class:
        class: Chamilo\CourseBundle\Tool\Group
        arguments:
            - group
            - interaction
            - group/group.php
            - group.gif

        tags:
            - { name: chamilo_course.tool }

    chamilo_course.tool.learning_path.class:
        class: Chamilo\CourseBundle\Tool\LearningPath
        arguments:
            - learnpath
            - authoring
            - newscorm/lp_controller.php
            - scorms.gif
        tags:
            - { name: chamilo_course.tool }

    chamilo_course.tool.link.class:
        class: Chamilo\CourseBundle\Tool\Link
        arguments:
            - link
            - authoring
            - link/link.php
            - links.gif

        tags:
            - { name: chamilo_course.tool }

    chamilo_course.tool.maintenance.class:
        class: Chamilo\CourseBundle\Tool\Maintenance
        arguments:
            - course_maintenance
            - admin
            - course_info/maintenance.php
            - backup.gif
        tags:
            - { name: chamilo_course.tool }

    chamilo_course.tool.settings.class:
        class: Chamilo\CourseBundle\Tool\Settings
        arguments:
            - course_setting
            - admin
            - course_info/infocours.php
            - reference.gif

        tags:
            - { name: chamilo_course.tool }

    chamilo_course.tool.survey.class:
        class: Chamilo\CourseBundle\Tool\Survey
        arguments:
            - survey
            - interaction
            - survey/survey_list.php
            - survey.gif

        tags:
            - { name: chamilo_course.tool }

    chamilo_course.tool.tracking.class:
        class: Chamilo\CourseBundle\Tool\Tracking
        arguments:
            - tracking
            - admin
            - tracking/courseLog.php
            - statistics.gif

        tags:
            - { name: chamilo_course.tool }

    chamilo_course.tool.user.class:
        class: Chamilo\CourseBundle\Tool\User
        arguments:
            - user
            - interaction
            - user/user.php
            - members.gif

        tags:
            - { name: chamilo_course.tool }

    chamilo_course.tool.wiki.class:
        class: Chamilo\CourseBundle\Tool\Wiki
        arguments:
            - wiki
            - interaction
            - wiki/index.php
            - wiki.gif
        tags:
            - { name: chamilo_course.tool }
