login_check:
    path: /login_check

logout:
    path: /logout

oneup_uploader:
    resource: .
    type: uploader

legacy_main:
    path: /main/{name}
    defaults: {_controller: 'ChamiloCoreBundle:Legacy:classic'}
    requirements:
        name: .+

legacy_plugin:
    path: /plugin/{name}
    defaults: {_controller: 'ChamiloCoreBundle:Legacy:plugin'}
    requirements:
        name: .+

courses_vue:
    path: /courses/{wildcard}
    controller: Chamilo\CoreBundle\Controller\IndexController::resources
    requirements:
        wildcard: .*

sessions_vue:
    path: /sessions/{wildcard}
    controller: Chamilo\CoreBundle\Controller\IndexController::resources
    requirements:
        wildcard: .*

resources_vue:
    path: /resources/{wildcard}
    controller: Chamilo\CoreBundle\Controller\IndexController::resources
    requirements:
        wildcard: .*

vue:
    path: /vue/{wildcard}
    controller: Chamilo\CoreBundle\Controller\IndexController::resources
    requirements:
        wildcard: .*

# web url shortcuts for legacy templates
web.ajax:
    path: main/inc/ajax/

web.main:
    path: main/

#liip_theme:
#    resource: "@LiipThemeBundle/Resources/config/routing.xml"
#    prefix: /theme

# Redirects /url/ to /url always located at the end
#remove_trailing_slash:
#    path: /{url}
#    defaults: {_controller: 'ChamiloCoreBundle:Redirecting:removeTrailingSlash'}
#    requirements:
#        url: .*/$
#        _method: GET

chamilo_graphql:
    resource: "@ChamiloGraphQlBundle/Resources/config/routing.yaml"

chamilo_lti:
    resource: "@ChamiloLtiBundle/Resources/config/routing.yml"
