secured_login_check:
    pattern:   /secured/login_check

secured_logout:
    pattern:   /secured/logout

logout:
    pattern:   /secured/logout

home:
    path:      /
    defaults:  { _controller: index.controller:indexAction, culture: en }

index:
    path:      /
    defaults:  { _controller: index.controller:indexAction, culture: en }

root:
    path:      /
    defaults:  { _controller: index.controller:indexAction, culture: en }

homepage:
    path:      /
    defaults:  { _controller: index.controller:indexAction, culture: en }

userportal:
    path:      /
    defaults:  { _controller: index.controller:userportalAction, culture: en }

example:
    resource: "src/ChamiloLMS/Resources/config/route_example.yml"
    prefix:   /example-route

javascript:
    path:      /ChamiloLMS/js

css:
    path:      /ChamiloLMS/css

