logout:
    path: /logout

_admin:
    resource: routes/sonata_admin.yaml
    prefix: /administration

sonata_admin_redirect:
    path: /administration/dashboard

sonata_admin_my_dashboard:
    path: /administration
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::redirectAction
    defaults:
        route: sonata_admin_dashboard
        permanent: false

sonata_user_admin_security_logout:
    path: /logout

app_document:
    resource: |
        alias: app.document
        path: /resource/documents
        form: Chamilo\CoreBundle\Form\Type\DocumentType
    type: sylius.resource

app_document_index:
    path: /resource/documents/
    methods: [GET,POST]
    defaults:
        _controller: app.controller.document:indexAction
        _sylius:
            template: ChamiloCoreBundle:Document:show.html.twig # Use a custom template.
#            repository:
#                method: findForStore # Use a custom repository method.
#                arguments: [$slug] # Pass the slug from the url to the repository.


#    type: sylius.resource_api

#admin_dashboard:
#    pattern: /administration/
#    defaults:
#        _controller: FrameworkBundle:Redirect:redirect
#        route: sonata_admin_dashboard
#        permanent: true # this for 301

#admin_without_locale:
#    pattern: /administration
#    defaults:
#        _controller: FrameworkBundle:Redirect:redirect
#        route: sonata_admin_dashboard
#        permanent: true # this for 301

#admin_dashboard_without_locale:
#    pattern: /administration/dashboard
#    defaults:
#        _controller: FrameworkBundle:Redirect:redirect
#        route: sonata_admin_dashboard
#        permanent: true
#_api:
#    resource: routing_api.yml
#    prefix:   /api

liip_theme:
    resource: "@LiipThemeBundle/Resources/config/routing.xml"
    prefix: /theme
