# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    app_env: '%env(APP_ENV)%'
    password_encryption: '%env(APP_ENCRYPT_METHOD)%'
    secret: '%env(APP_SECRET)%'
    locale: '%env(APP_LOCALE)%'
    installed: '%env(APP_INSTALLED)%'
    twig:
        form:
            resources:
                - 'GeneratorBundle::fields.html.twig'
    course_info_is_not_editable: false

#    sonata_media.cdn.host: '/var/upload/media/'
#    sonata_page.varnish.command: 'if [ ! -r "/etc/varnish/secret" ]; then echo "VALID ERROR :/"; else varnishadm -S /etc/varnish/secret -T 127.0.0.1:6082 {{ COMMAND }} "{{ EXPRESSION }}"; fi;'
#    router.request_context.base_url: '%env(APP_URL_APPEND)%'
#    asset.request_context.base_path: '%env(APP_URL_APPEND)%'

    glide_media_filters:
        editor_thumbnail:
            w: 64
            h: 64
        user_picture_small:
            w: 48
            h: 48
        user_picture_profile:
            w: 94
            h: 94
        course_picture_small:
            w: 85
            h: 47
        course_picture_medium:
            w: 400
            h: 225
        resource_show_preview:
            w: 500

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        public: true       # Allows optimizing the container by removing unused services; this also means
          # fetching services directly from the container via $container->get() won't work.
        # The best practice is to be explicit about your dependencies anyway.

    Chamilo\CoreBundle\Component\Utils\Glide:
        arguments:
            - {source: '@oneup_flysystem.resources_filesystem', cache: '@oneup_flysystem.cache_resources_filesystem'}
            - '%glide_media_filters%'

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name

    Vich\UploaderBundle\Naming\SubdirDirectoryNamer:
        public: true

    Chamilo\CoreBundle\Controller\ResourceController:
        arguments:
            - '@Chamilo\CoreBundle\Repository\ResourceFactory'
#            - '@Chamilo\CoreBundle\Block\BreadcrumbBlockService'

    Symfony\Component\Mailer\Mailer:
        public: true

    Doctrine\ORM\EntityManager: "@doctrine.orm.default_entity_manager"

    chamilo_core.hook_factory:
        class: 'Chamilo\CoreBundle\Hook\HookFactory'

    chamilo_lti_utils:
        class: Chamilo\LtiBundle\Util\Utils
        arguments: ['@chamilo.settings.manager']

    apy_grid.factory:
        class: APY\DataGridBundle\Grid\GridFactory
        arguments: ['@service_container', '@apy_grid.registry']
        public: true

    apy_grid.registry:
        class: APY\DataGridBundle\Grid\GridRegistry
        public: true

    League\Flysystem\MountManager: '@oneup_flysystem.mount_manager'

    # Voters
    # Group voter, checks if a user has permissions to do actions
    chamilo_course.security.authorization.voter.group_voter:
        class: Chamilo\CoreBundle\Security\Authorization\Voter\GroupVoter
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@Chamilo\CoreBundle\Repository\CourseRepository'
            - '@Chamilo\CourseBundle\Repository\CGroupInfoRepository'
            - '@security.authorization_checker'
            - '@service_container'
        public: false
        tags:
            - {name: security.voter}

sylius_settings:
    driver: doctrine/orm

# Doctrine audit
#sonata_doctrine_orm_admin:
#    audit:
#        force: false # Audits are set in the admin.yml files with audit:true

# Grid default template
apy_data_grid:
    theme: '@ChamiloCore/Resource/grid_theme.html.twig'
    limits: [20, 50, 100]
    persistence: false
#    no_data_message: "No data"
#    no_result_message: "No result"
#    actions_columns_size: -1
#    actions_columns_title: "Actions"
#    actions_columns_separator: "<br />"
    pagerfanta:
        enable: true
        view_class: 'Pagerfanta\View\TwitterBootstrap4View'
        options:
            prev_message: "«"
            next_message: "»"

# Course settings
chamilo_course:
    driver: doctrine/orm

gregwar_captcha:
    width: 200
    height: 50
    length: 6

cocur_slugify:
    lowercase: true

imports:
    - {resource: ../src/CoreBundle/Resources/config/services.yml}
