# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    app_env: '%env(APP_ENV)%'
    password_encryption: '%env(APP_ENCRYPT_METHOD)%'
    secret: '%env(APP_SECRET)%'
    locale: '%env(APP_LOCALE)%'
    installed: '%env(APP_INSTALLED)%'
    container.dumper.inline_factories: true
    twig:
        form:
            resources:
                - 'GeneratorBundle::fields.html.twig'
    course_info_is_not_editable: false

    #    router.request_context.base_url: '%env(APP_URL_APPEND)%'
    #    asset.request_context.base_path: '%env(APP_URL_APPEND)%'

    # See https://glide.thephpleague.com/1.0/api/quick-reference/
    glide_media_filters:
        editor_thumbnail:
            w: 64
            h: 64
        user_picture_small:
            w: 48
            h: 48
        user_picture_profile:
            w: 94
            h: 94
        course_picture_small:
            w: 85
            h: 47
        course_picture_medium:
            w: 400
            h: 225
        resource_show_preview:
            w: 500

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        public: true       # Allows optimizing the container by removing unused services; this also means
        # fetching services directly from the container via $container->get() won't work.
        # The best practice is to be explicit about your dependencies anyway.

#    App\ApiPlatform\AutoGroupResourceMetadataFactory:
#        # causes this to decorate around the cached factory so that
#        # our service is never cached (which, of course, can have performance
#        # implications!
#        decoration_priority: -20

    Chamilo\CoreBundle\Component\Utils\AssetDirectoryNamer: ~
    Chamilo\CoreBundle\Component\Utils\NameConvention: ~
    Chamilo\CoreBundle\Component\Utils\Glide:
        arguments:
            - {source: '@oneup_flysystem.resources_filesystem', cache: '@oneup_flysystem.cache_resources_filesystem'}
            - '%glide_media_filters%'

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name

    Vich\UploaderBundle\Naming\SubdirDirectoryNamer:
        public: true

    Chamilo\CoreBundle\Controller\ResourceController:
        arguments:
            - '@Chamilo\CoreBundle\Repository\ResourceFactory'

    Symfony\Component\Mailer\Mailer:
        public: true

    Doctrine\ORM\EntityManager: "@doctrine.orm.default_entity_manager"

    chamilo_core.hook_factory:
        class: 'Chamilo\CoreBundle\Hook\HookFactory'

    chamilo_lti_utils:
        class: Chamilo\LtiBundle\Util\Utils
        arguments: ['@chamilo.settings.manager']

    League\Flysystem\MountManager: '@oneup_flysystem.mount_manager'

    Chamilo\CoreBundle\EventListener\HTTPExceptionListener:
        tags:
            - {name: kernel.event_listener, event: kernel.exception}

    Chamilo\CoreBundle\EventListener\ExceptionListener:
        arguments: ['@twig']
        tags:
            - {name: kernel.event_listener, event: kernel.exception}

sylius_settings:
    driver: doctrine/orm

# Course settings
chamilo_course:
    driver: doctrine/orm

# gregwar_captcha:
    #     width: 200
    #     height: 50
    #   length: 6

cocur_slugify:
    lowercase: true

imports:
    - {resource: ../src/CoreBundle/Resources/config/services.yml}
