# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    password_encryption: '%env(APP_ENCRYPT_METHOD)%'
    secret: '%env(APP_SECRET)%'
    locale: '%env(APP_LOCALE)%'
    url_append: '%env(APP_URL_APPEND)%'
    installed: '%env(APP_INSTALLED)%'
    twig:
        form:
            resources:
                - 'GeneratorBundle::fields.html.twig'

    mailer_transport: smtp
    mailer_host: 127.0.0.1
    mailer_user: admin@example.com
    mailer_password: null
    course_info_is_not_editable: false
    sonata_media.cdn.host: '%env(APP_URL_APPEND)%/public/resource'
    sonata_page.varnish.command: 'if [ ! -r "/etc/varnish/secret" ]; then echo "VALID ERROR :/"; else varnishadm -S /etc/varnish/secret -T 127.0.0.1:6082 {{ COMMAND }} "{{ EXPRESSION }}"; fi;'
    router.request_context.base_url: '%env(APP_URL_APPEND)%'
    asset.request_context.base_path: '%env(APP_URL_APPEND)%'

    glide_config:
        source: 'oneup_flysystem.resources_filesystem'
        cache: 'oneup_flysystem.cache_resources_filesystem'
        #cache: 'var/cache/resource/'

    glide_media_filters:
        user_picture_small:
            w: 48
            h: 48
        user_picture_profile:
            w: 94
            h: 94
        course_picture_small:
            w: 85
            h: 47
        course_picture_medium:
            w: 400
            h: 225
        resource_show_preview:
            w: 500

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        public: true       # Allows optimizing the container by removing unused services; this also means
          # fetching services directly from the container via $container->get() won't work.
        # The best practice is to be explicit about your dependencies anyway.
        bind:
            $passwordEncrypt: '%password_encryption%'

    Chamilo\CoreBundle\Component\Utils\Glide:
        arguments:
            - {source: '@oneup_flysystem.resources_filesystem', cache: '@oneup_flysystem.cache_resources_filesystem'}
            - '%glide_media_filters%'

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    _instanceof:
        Sylius\Bundle\ResourceBundle\Controller\ResourceController:
            autowire: false

    Chamilo\PageBundle\:
        resource: '../src/PageBundle/*'
        exclude: '../src/PageBundle/{Entity,Migrations,Tests}'
        public: true

    Vich\UploaderBundle\Naming\SubdirDirectoryNamer:
        public: true

    Chamilo\CoreBundle\Component\Naming\SmartUniqueNamer:
        public: true


    Chamilo\CoreBundle\Controller\ResourceController:
        arguments:
            - '@League\Flysystem\MountManager'
            - '@Chamilo\CoreBundle\ToolChain'
            - '@translator.default'
            - '@Chamilo\CoreBundle\Block\BreadcrumbBlockService'

    Chamilo\ThemeBundle\:
        autowire: true
        resource: '../src/ThemeBundle/*'
        exclude: '../src/ThemeBundle/{Entity,Migrations,Tests}'
        public: true

    Chamilo\ThemeBundle\Controller\ExceptionController:
        public: true
        arguments:
            $debug: '%kernel.debug%'

    Doctrine\ORM\EntityManager: "@doctrine.orm.default_entity_manager"

    chamilo_core.hook_factory:
        class: 'Chamilo\CoreBundle\Hook\HookFactory'

        # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    AdminBundle\:
        resource: '../src/AdminBundle/*'
        # you can exclude directories or files
        # but if a service is unused, it's removed anyway
        exclude: '../src/AdminBundle/{ChamiloAdminBundle.php,Entity,Repository,Tests}'

    ClassificationBundle\:
        resource: '../src/ClassificationBundle/*'
        # you can exclude directories or files
        # but if a service is unused, it's removed anyway
        exclude: '../src/ClassificationBundle/{ChamiloClassificationBundle.php,Entity,Admin,Document,Repository,Tests}'

    ContactBundle\:
        resource: '../src/ContactBundle/*'
        # you can exclude directories or files
        # but if a service is unused, it's removed anyway
        exclude: '../src/ContactBundle/{ChamiloContactBundle.php,Entity,Admin,Controller,DependencyInjection,Form,Repository,Tests}'

    Chamilo\UserBundle\:
        resource: '../src/UserBundle/*'
        # you can exclude directories or files
        # but if a service is unused, it's removed anyway
        exclude: '../src/UserBundle/{Admin,ChamiloUserBundle.php,Security/FOSUBUserProvider.php,DependencyInjection,Form,EventListener,Entity,Repository}'

    chamilo_lti_utils:
        class: Chamilo\LtiBundle\Util\Utils
        arguments: ['@chamilo.settings.manager']

    apy_grid.factory:
        class: APY\DataGridBundle\Grid\GridFactory
        arguments: ['@service_container', '@apy_grid.registry']
        public: true

    apy_grid.registry:
        class: APY\DataGridBundle\Grid\GridRegistry
        public: true

sylius_settings:
    driver: doctrine/orm

# Doctrine audit
sonata_doctrine_orm_admin:
    audit:
        force: false # Audits are set in the admin.yml files with audit:true

# Grid default template
apy_data_grid:
    theme: '@ChamiloTheme/Resource/grid_theme.html.twig'
    limits: [20, 50, 100]
    persistence: false
#    no_data_message: "No data"
#    no_result_message: "No result"
#    actions_columns_size: -1
#    actions_columns_title: "Actions"
#    actions_columns_separator: "<br />"
#    pagerfanta:
#        enable: false
#        view_class: "Pagerfanta\View\DefaultView"
#        options:
#            prev_message: "«"
#            next_message: "»"

# Course settings
chamilo_course:
    driver: doctrine/orm

gregwar_captcha:
    width: 200
    height: 50
    length: 6

imports:
    - {resource: ../src/CoreBundle/Resources/config/services.yml}
    - {resource: ../src/PageBundle/Resources/config/services.yml}
    - {resource: ../vendor/knplabs/doctrine-behaviors/config/orm-services.yml}

sylius_resource:
    resources:
        app.exercise_category:
            driver: 'doctrine/orm'
            classes:
                model: 'Chamilo\CourseBundle\Entity\CExerciseCategory'

cocur_slugify:
    lowercase: true
