services:
    _defaults:
        autowire: true
        public: true

    chamilo_user.security.user_provider:
        class: Chamilo\UserBundle\Security\FOSUBUserProvider
        arguments:
            - '@sonata.user.orm.user_manager'
            - {facebook: facebookId, google: googleId, github: githubId}

    chamilo_user.security.login_form_authenticator:
        class: Chamilo\UserBundle\Security\LoginFormAuthenticator

    Chamilo\UserBundle\Repository\UserRepository:
        arguments:
            $tool: 'global'
            $type: 'users'
        # call a method on the specified factory service
        factory: ['@Chamilo\CoreBundle\Repository\ResourceFactory', 'createRepository']

    Chamilo\UserBundle\Repository\GroupRepository: ~
