services:
    chamilo_user_provider:
        class: Chamilo\UserBundle\Security\FOSUBUserProvider
        #this is the place where the properties are passed to the UserProvider - see config.yml
        arguments: ['@sonata.user.orm.user_manager', {facebook: facebookId, google: googleId, github: githubId} ]