services:
  chamilo_user_provider:
    class: Chamilo\UserBundle\Security\FOSUBUserProvider
    arguments:
      - '@sonata.user.orm.user_manager'
      - { facebook: facebookId, google: googleId, github: githubId }
