UserStatus:
    type: enum
    config:
        description: "One of the statuses for the user."
        values:
            TEACHER:
                description: "Global status of a user: Course Manager."
                value: '@=constant("Chamilo\\UserBundle\\Entity\\User::TEACHER")'
            SESSION_ADMIN:
                description: "Global status of a user: Session Admin."
                value: '@=constant("Chamilo\\UserBundle\\Entity\\User::SESSION_ADMIN")'
            DRH:
                description: "Global status of a user: Human Ressource Manager."
                value: '@=constant("Chamilo\\UserBundle\\Entity\\User::DRH")'
            STUDENT:
                description: "Global status of a user: Student."
                value: '@=constant("Chamilo\\UserBundle\\Entity\\User::STUDENT")'

ImageSize:
    type: enum
    config:
        description: 'One of the sizes for the picture.'
        values:
            SIZE_TINY:
                description: 'Image in small size: 16px.'
                value: '@=constant("ICON_SIZE_TINY")'
            SIZE_SMALL:
                description: 'Image in small size: 22px.'
                value: '@=constant("ICON_SIZE_SMALL")'
            SIZE_MEDIUM:
                description: 'Image in small size: 32px.'
                value: '@=constant("ICON_SIZE_MEDIUM")'
            SIZE_LARGE:
                description: 'Image in small size: 48px.'
                value: '@=constant("ICON_SIZE_LARGE")'
            SIZE_BIG:
                description: 'Image in small size: 64px.'
                value: '@=constant("ICON_SIZE_BIG")'
            SIZE_HUGE:
                description: 'Image in small size: 128px.'
                value: '@=constant("ICON_SIZE_HUGE")'

CourseToolType:
    type: enum
    config:
        description: 'One of the types of course tool'
        values:
            TOOL_DESCRIPTION:
                value: '@=constant("TOOL_COURSE_DESCRIPTION")'
            TOOL_ANNOUNCEMENT:
                value: '@=constant("TOOL_ANNOUNCEMENT")'
