Query:
    type: object
    config:
        description: "GraphQL queries."
        fields:
            viewer:
                description: "A registered user on the platform."
                type: "User"
                resolve: '@=resolver("viewer")'
            course:
                description: 'Get the data from a course on the platform.'
                type: 'Course'
                args:
                    id:
                        type: 'Int!'
                resolve: "@=resolver('course', [args['id'], context])"
            session:
                description: 'Get the data from a session on the platform.'
                type: 'Session'
                args:
                    id:
                        type: 'Int!'
                resolve: "@=resolver('session', [args['id'], context])"
            sessionCategory:
                description: 'Get the data from a session category.'
                type: 'SessionCategory'
                args:
                    id:
                        type: 'Int!'
                resolve: "@=resolver('sessioncategory', [args['id'], context])"

User:
    type: object
    config:
        description: "Registered user."
        resolveField: '@=resolver("Chamilo\\ApiBundle\\GraphQL\\Resolver\\UserResolver", [value, args, info, context])'
        fields:
            id:
                description: "The unique ID of the user."
                type: "Int"
            firstname:
                type: "String"
            lastname:
                type: "String"
            username:
                type: "String"
            email:
                type: "String"
            officialCode:
                type: "String"
            status:
                type: "UserStatus"
            picture:
                type: "String"
                args:
                    size:
                        type: "ImageSize"
                        defaultValue: '@=constant("ICON_SIZE_MEDIUM")'
            messages:
                description: 'Received messages for the user.'
                type: '[UserMessage]'
                args:
                    lastId:
                        description: 'Last received by the app message ID.'
                        type: 'Int'
                        defaultValue: 0
            messageContacts:
                description: 'Get potential users to send a message for the current user.'
                type: '[User]'
                args:
                    filter:
                        description: 'The search text to filter the user list.'
                        type: 'String!'
            courses:
                description: 'Course list for the current user.'
                type: '[Course]'
            sessions:
                description: 'Session list for the current user.'
                type: '[Session]'

UserMessage:
    type: object
    config:
        description: 'Received message by user.'
        resolveField: '@=resolver("Chamilo\\ApiBundle\\GraphQL\\Resolver\\MessageResolver", [value, args, info, context])'
        fields:
            id:
                description: 'The unique ID of the message.'
                type: 'Int'
            title:
                type: 'String'
            content:
                type: 'String'
            sender:
                type: 'User'
            sendDate:
                type: 'DateTime'
            excerpt:
                type: 'String'
                args:
                    length:
                        description: 'The approximate desired length. 50 chars by default.'
                        type: 'Int'
                        defaultValue: 50
            hasAttachments:
                type: 'Boolean'

Course:
    type: object
    config:
        description: 'A course registered on the platform.'
        resolveField: '@=resolver("Chamilo\\ApiBundle\\GraphQL\\Resolver\\CourseResolver", [value, args, info, context])'
        fields:
            id:
                description: 'The unique ID of the course.'
                type: 'Int'
            title:
                type: 'String'
            code:
                type: 'String'
            categoryCode:
                type: 'String'
            directory:
                type: 'String'
            picture:
                type: 'String'
                args:
                    fullSize:
                        description: 'It indicates whether to get the full-sized image.'
                        type: 'Boolean'
                        defaultValue: false
            teachers:
                description: 'Teachers list in course. Or tutors list from course in session.'
                type: "[User]"
            tools:
                description: 'List of available tools for student view.'
                type: '[CourseTool]'

SessionCategory:
    type: object
    config:
        description: 'A session category.'
        resolveField: '@=resolver("Chamilo\\ApiBundle\\GraphQL\\Resolver\\SessionCategoryResolver", [value, args, info, context])'
        fields:
            id:
                description: 'The unique ID of the category.'
                type: 'Int'
            name:
                type: 'String'
            startDate:
                type: 'DateTime'
            endDate:
                type: 'DateTime'

Session:
    type: object
    config:
        description: 'A session registered on the platform.'
        resolveField: '@=resolver("Chamilo\\ApiBundle\\GraphQL\\Resolver\\SessionResolver", [value, args, info, context])'
        fields:
            id:
                description: 'The unique ID of the session.'
                type: 'Int'
            name:
                type: 'String'
            category:
                type: 'SessionCategory'
            description:
                type: 'String'
            numberOfCourses:
                type: 'Int'
            numberOfUsers:
                type: 'Int'
            duration:
                type: 'Int'
            displayStartDate:
                type: 'DateTime'
            displayEndDate:
                type: 'DateTime'
            accessStartDate:
                type: 'DateTime'
            accessEndDate:
                type: 'DateTime'
            coachAccessStartDate:
                type: 'DateTime'
            coachAccessEndDate:
                type: 'DateTime'
            generalCoach:
                type: 'User'
            courses:
                type: '[Course]'

CourseTool:
    type: union
    config:
        description: 'Course tools'
        resolveType: '@=resolver("Chamilo\\ApiBundle\\GraphQL\\Resolver\\CourseToolResolver", [value])'
        types: [ToolDescription, ToolAnnouncements]

ToolDescription:
    type: object
    config:
        description: 'Global summary of the course.'
        resolveField: '@=resolver("Chamilo\\ApiBundle\\GraphQL\\Resolver\\ToolDescriptionResolver", [value, args, info, context])'
        fields:
            name:
                type: 'String'
            category:
                type: 'String'
            image:
                type: 'String'
            customIcon:
                type: 'String'
            isVisible:
                type: 'Boolean'
            descriptions:
                type: '[CourseDescription]!'

CourseDescription:
    type: object
    config:
        description: 'A section for the course description.'
        resolveField: '@=resolver("Chamilo\\ApiBundle\\GraphQL\\Resolver\\CourseDescriptionResolver", [value, args, info, context])'
        fields:
            id:
                type: 'Int'
            title:
                type: 'String'
            content:
                type: 'String'
            type:
                type: 'Int'

ToolAnnouncements:
    type: object
    config:
        description: 'Announcements related to the course.'
        resolveField: '@=resolver("Chamilo\\ApiBundle\\GraphQL\\Resolver\\ToolAnnouncementsResolver", [value, args, info, context])'
        fields:
            name:
                type: 'String'
            category:
                type: 'String'
            image:
                type: 'String'
            customIcon:
                type: 'String'
            isVisible:
                type: 'Boolean'
            announcements:
                type: '[CourseAnnouncement]!'

CourseAnnouncement:
    type: object
    config:
        description: 'Course announcement.'
        resolveField: '@=resolver("Chamilo\\ApiBundle\\GraphQL\\Resolver\\CourseAnnouncementResolver", [value, args, info, context])'
        fields:
            id:
                type: 'Int'
            title:
                type: 'String'
            content:
                type: 'String'
            by:
                type: 'User'
            lastUpdateDate:
                type: 'DateTime'
