Course:
    type: object
    config:
        description: 'A course registered on the platform.'
        fields:
            tools:
                description: 'List of available tools for student view.'
                type: '[CourseTool]'
                args:
                    type:
                        description: 'Filter by one type of tool'
                        type: 'CourseToolType'

CourseTool:
    type: union
    config:
        description: 'Course tools'
        resolveType: '@=resolver("Chamilo\\ApiBundle\\GraphQL\\Resolver\\CourseToolResolver", [value])'
        types: [ToolDescription, ToolAnnouncements]

ToolDescription:
    type: object
    config:
        description: 'Global summary of the course.'
        resolveField: '@=resolver("Chamilo\\ApiBundle\\GraphQL\\Resolver\\ToolDescriptionResolver", [value, args, info, context])'
        fields:
            name:
                type: 'String'
            category:
                type: 'String'
            image:
                type: 'String'
            customIcon:
                type: 'String'
            isVisible:
                type: 'Boolean'
            descriptions:
                type: '[CourseDescription]!'

CourseDescription:
    type: object
    config:
        description: 'A section for the course description.'
        resolveField: '@=resolver("Chamilo\\ApiBundle\\GraphQL\\Resolver\\CourseDescriptionResolver", [value, args, info, context])'
        fields:
            id:
                type: 'Int'
            title:
                type: 'String'
            content:
                type: 'String'
            type:
                type: 'Int'

ToolAnnouncements:
    type: object
    config:
        description: 'Announcements related to the course.'
        resolveField: '@=resolver("Chamilo\\ApiBundle\\GraphQL\\Resolver\\ToolAnnouncementsResolver", [value, args, info, context])'
        fields:
            name:
                type: 'String'
            category:
                type: 'String'
            image:
                type: 'String'
            customIcon:
                type: 'String'
            isVisible:
                type: 'Boolean'
            announcements:
                type: '[CourseAnnouncement]!'

CourseAnnouncement:
    type: object
    config:
        description: 'Course announcement.'
        resolveField: '@=resolver("Chamilo\\ApiBundle\\GraphQL\\Resolver\\CourseAnnouncementResolver", [value, args, info, context])'
        fields:
            id:
                type: 'Int'
            title:
                type: 'String'
            content:
                type: 'String'
            by:
                type: 'User'
            lastUpdateDate:
                type: 'DateTime'
