Query:
    type: object
    config:
        description: "GraphQL queries."
        fields:
            viewer:
                description: "A registered user on the platform."
                type: "User"
                resolve: "@=resolver('viewer', [context])"
            course:
                description: 'Get the data from a course on the platform.'
                type: 'Course'
                args:
                    id:
                        type: 'Int!'
                resolve: "@=resolver('course', [args['id'], context])"

User:
    type: object
    config:
        description: "Registered user."
        fields:
            id:
                description: "The unique ID of the user."
                type: "Int"
            firstname:
                type: "String"
            lastname:
                type: "String"
            username:
                type: "String"
            email:
                type: "String"
                resolve: "@=resolver('user_email', [value, context])"
            officialCode:
                type: "String"
            status:
                type: "UserStatus"
            picture:
                type: "String"
                args:
                    size:
                        type: "ImageSize"
                        defaultValue: '@=constant("ICON_SIZE_MEDIUM")'
                resolve: "@=resolver('user_picture', [value, args['size']])"
            messages:
                description: 'Received messages for the user.'
                type: '[UserMessage]'
                args:
                    lastId:
                        description: 'Last received by the app message ID.'
                        type: 'Int'
                        defaultValue: 0
                resolve: "@=resolver('user_messages', [value, args['lastId'], context])"
            messageContacts:
                description: 'Get potential users to send a message for the current user.'
                type: '[User]'
                args:
                    filter:
                        description: 'The search text to filter the user list.'
                        type: 'String!'
                resolve: "@=resolver('user_message_contacts', [value, args['filter'], context])"
            courses:
                description: 'Course list for the current user.'
                type: '[Course]'
                resolve: "@=resolver('user_courses', [value, context])"

UserMessage:
    type: object
    config:
        description: 'Received message by user.'
        fields:
            id:
                description: 'The unique ID of the message.'
                type: 'Int'
            title:
                type: 'String'
            content:
                type: 'String'
            sender:
                type: 'User'
                resolve: "@=resolver('message_sender', [value])"
            sendDate:
                type: 'DateTime'
            excerpt:
                type: 'String'
                args:
                    length:
                        description: 'The approximate desired length. 50 chars by default.'
                        type: 'Int'
                        defaultValue: 50
                resolve: "@=resolver('message_excerpt', [value, args['length']])"
            hasAttachments:
                type: 'Boolean'
                resolve: "@=resolver('message_has_attachments', [value])"

Course:
    type: object
    config:
        description: 'A course registered on the platform.'
        fields:
            id:
                description: 'The unique ID of the course.'
                type: 'Int'
            title:
                type: 'String'
            code:
                type: 'String'
            categoryCode:
                type: 'String'
            picture:
                type: 'String'
                args:
                    fullSize:
                        description: 'It indicates whether to get the full-sized image.'
                        type: 'Boolean'
                        defaultValue: false
                resolve: "@=resolver('course_picture', [value, args['fullSize']])"
            teachers:
                description: 'Teachers list in course.'
                type: "[User]"
                resolve: "@=resolver('course_teachers', [value])"
            tools:
                description: 'List of names from available tools for student view.'
                type: '[String]'
                resolve: "@=resolver('course_tools', [value, context])"
