services:
    sonata.admin.course:
        class: Chamilo\CoreBundle\Admin\CourseAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "LMS", label: "Course" }
        arguments:
            - ~
            - Chamilo\CoreBundle\Entity\Course
            - ~
        calls:
            - [ setTranslationDomain, [ChamiloCoreBundle]]
            - [ setToolChain, [@chamilo_course.tool_chain]]

    sonata.admin.session:
        class: Chamilo\CoreBundle\Admin\SessionAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "LMS", label: "Session" }
        arguments:
            - ~
            - Chamilo\CoreBundle\Entity\Session
            - ~
        calls:
            - [ setTranslationDomain, [ChamiloCoreBundle]]

    sonata.admin.session_category:
        class: Chamilo\CoreBundle\Admin\SessionCategoryAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "LMS", label: "Session category" }
        arguments:
            - ~
            - Chamilo\CoreBundle\Entity\SessionCategory
            - ~
        calls:
            - [ setTranslationDomain, [ChamiloCoreBundle]]

    sonata.admin.career:
        class: Chamilo\CoreBundle\Admin\SessionCategoryAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "LMS", label: "Session category" }
        arguments:
            - ~
            - Chamilo\CoreBundle\Entity\SessionCategory
            - ~
        calls:
            - [ setTranslationDomain, [ChamiloCoreBundle]]
    sonata.admin.promotion:
        class: Chamilo\CoreBundle\Admin\SessionCategoryAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "LMS", label: "Session category" }
        arguments:
            - ~
            - Chamilo\CoreBundle\Entity\SessionCategory
            - ~
        calls:
            - [ setTranslationDomain, [ChamiloCoreBundle]]
    sonata.admin.course_rel_user:
        class: Chamilo\CoreBundle\Admin\CourseRelUserAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "LMS", label: "CourseRelUser" }
        arguments:
            - ~
            - Chamilo\CoreBundle\Entity\CourseRelUser
            - ~
        calls:
            - [ setTranslationDomain, [ChamiloCoreBundle]]

    sonata.admin.session_rel_course:
        class: Chamilo\CoreBundle\Admin\SessionRelCourseAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "LMS", label: "SessionRelCourseAdmin" }
        arguments:
            - ~
            - Chamilo\CoreBundle\Entity\SessionRelCourse
            - ~
        calls:
            - [ setTranslationDomain, [ChamiloCoreBundle]]

    sonata.admin.session_rel_user:
            class: Chamilo\CoreBundle\Admin\SessionRelUserAdmin
            tags:
                - { name: sonata.admin, manager_type: orm, group: "LMS", label: "SessionRelUserAdmin" }
            arguments:
                - ~
                - Chamilo\CoreBundle\Entity\SessionRelUser
                - ~
            calls:
                - [ setTranslationDomain, [ChamiloCoreBundle]]

    sonata.admin.access_url:
        class: Chamilo\CoreBundle\Admin\AccessUrlAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "LMS", label: "AccessUrlAdmin" }
        arguments:
            - ~
            - Chamilo\CoreBundle\Entity\AccessUrl
            - ~
        calls:
            - [ setTranslationDomain, [ChamiloCoreBundle]]

    sonata.admin.access_url_rel_course:
        class: Chamilo\CoreBundle\Admin\AccessUrlRelCourseAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "LMS", label: "AccessUrlRelCourseAdmin" }
        arguments:
            - ~
            - Chamilo\CoreBundle\Entity\AccessUrlRelCourse
            - ~
        calls:
            - [ setTranslationDomain, [ChamiloCoreBundle]]

    sonata.admin.user_field:
        class: Chamilo\UserBundle\Admin\UserField
        tags:
            - { name: sonata.admin, manager_type: orm, group: "LMS", label: "UserField" }
        arguments:
            - ~
            - Chamilo\CoreBundle\Entity\UserField
            - ~
        calls:
            - [ setTranslationDomain, [ChamiloCoreBundle]]

    sonata.admin.user_field_values:
        class: Chamilo\UserBundle\Admin\UserFieldValuesAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "LMS", label: "UserFieldValues" }
        arguments:
            - ~
            - Chamilo\CoreBundle\Entity\UserFieldValues
            - ~
        calls:
            - [ setTranslationDomain, [ChamiloCoreBundle]]

    sonata.admin.settings_current:
        class: Chamilo\CoreBundle\Admin\SettingsCurrentAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "LMS", label: "Settings" }
        arguments:
            - ~
            - Chamilo\CoreBundle\Entity\SettingsCurrent
            - ~
        calls:
            - [ setTranslationDomain, [ChamiloCoreBundle]]

    sonata.admin.user_group:
        class: Chamilo\CoreBundle\Admin\UserGroupAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "LMS", label: "UserGroupAdmin" }
        arguments:
            - ~
            - Chamilo\CoreBundle\Entity\UserGroup
            - ~
        calls:
            - [ setTranslationDomain, [ChamiloCoreBundle]]

    sonata.admin.user_group_rel_user:
        class: Chamilo\CoreBundle\Admin\UsergroupRelUser
        tags:
            - { name: sonata.admin, manager_type: orm, group: "LMS", label: "UsergroupRelUser" }
        arguments:
            - ~
            - Chamilo\CoreBundle\Entity\UsergroupRelUser
            - ~
        calls:
            - [ setTranslationDomain, [ChamiloCoreBundle]]

    sonata.admin.course_category:
        class: Chamilo\CoreBundle\Admin\CourseCategoryAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "LMS", label: "CourseCategoryAdmin" }
        arguments:
            - ~
            - Chamilo\CoreBundle\Entity\CourseCategory
            - ~
        calls:
            - [ setTranslationDomain, [ChamiloCoreBundle]]

    sonata.admin.course_request:
        class: Chamilo\CoreBundle\Admin\CourseRequestAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "LMS", label: "CourseRequestAdmin" }
        arguments:
            - ~
            - Chamilo\CoreBundle\Entity\CourseRequest
            - ~
        calls:
            - [ setTranslationDomain, [ChamiloCoreBundle]]
