parameters:
    chamilo.manager.course.class: Chamilo\CoreBundle\Entity\CourseManager
    chamilo.manager.course.entity: Chamilo\CoreBundle\Entity\Course

services:
    chamilo.manager.course:
        class: %chamilo.manager.course.class%
        arguments: [%chamilo.manager.course.entity%, @doctrine]

    chamilo.form.type.yes_no:
        class: Chamilo\CoreBundle\Form\Type\YesNoType
        tags:
            - { name: form.type, alias: yes_no }

#    chamilo.doctrine.entity_listener_resolver:
#        class: Chamilo\CoreBundle\Doctrine\EntityListenerResolver
#        arguments: [ "@service_container" ]

    chamilo.entity_listener.course:
        class: Chamilo\CoreBundle\Entity\Listener\CourseListener
        arguments: [ @chamilo.tool_chain ]
        tags:
            - { name: doctrine.orm.entity_listener }
#            - { name: doctrine.event_listener, event: prePersist }

    html_editor:
        class: Chamilo\CoreBundle\Component\Editor\CkEditor\CkEditor
        arguments: [@translator, @router]

    twig.extension.chamilo_extension:
        class: Chamilo\CoreBundle\Twig\Extension\ChamiloExtension
        tags:
            - { name: twig.extension }

    listener.request_response:
        class: Chamilo\CoreBundle\EventListener\LegacyListener
        arguments: [@service_container]
        tags:
          - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }
          - { name: kernel.event_listener, event: kernel.response, method: onKernelResponse }
          - { name: kernel.event_listener, event: kernel.controller, method: onKernelController }

    listener.locale:
        class: Chamilo\CoreBundle\EventListener\LocaleListener
        arguments: ["%kernel.default_locale%"]
        tags:
            - { name: kernel.event_subscriber }

    listener.navbar_menu_listener:
        class: Chamilo\CoreBundle\EventListener\MenuListener
        arguments: [@service_container]
        tags:
            - { name: kernel.event_listener, event: theme.sidebar_setup_menu_knp, method: onSetupMenu }

    listener.navbar_user_listener:
        class: Chamilo\CoreBundle\EventListener\ShowUserListener
        arguments: [@service_container]
        tags:
            - { name: kernel.event_listener, event: theme.navbar_user, method: onShowUser }
            - { name: kernel.event_listener, event: theme.sidebar_user, method: onShowUser }

    listener.message_listener:
        class: Chamilo\CoreBundle\EventListener\MessageListener
        arguments: [@service_container]
        tags:
            - { name: kernel.event_listener, event: theme.messages, method: onListMessages }

    listener.login_success_handler:
        class: Chamilo\CoreBundle\EventListener\LoginSuccessHandler
        arguments:  [@database_connection, @router, @security.context]

    listener.logout_success_handler:
        class: Chamilo\CoreBundle\EventListener\LogoutSuccessHandler
        arguments:  [@database_connection, @router, @security.context]

    # ORMs
    chamilo.coursebundle.course:
        class: Chamilo\CourseBundle\Entity\CourseManager
        arguments: [@doctrine]

    # Course block
    chamilo.corebundle.block.course:
        class: Chamilo\CoreBundle\Block\CourseBlockService
        arguments: ["course_block", @templating ]
        tags:
            - { name: sonata.block }

    # Course block
    chamilo.corebundle.block.header:
        class: Chamilo\CoreBundle\Block\CourseBlockService
        arguments: ["header", @templating ]
        tags:
            - { name: sonata.block }

    # Menus

    chamilo.menu.simple_menu:
        class: Chamilo\CoreBundle\Menu\SimpleMenuBuilder
        arguments: [@service_container]

    chamilo.corebundle.menu.main_menu_builder:
        class: Chamilo\CoreBundle\Menu\MainMenuBuilder
        arguments: [@knp_menu.factory, @router]

    chamilo.corebundle.menu.course_builder:
        class: Chamilo\CoreBundle\Menu\CourseMenuBuilder
        arguments: [@knp_menu.factory, @chamilo.coursebundle.course, @router]

    # Blocks
    chamilo.corebundle.block.main_menu:
        class: Chamilo\CoreBundle\Block\MainMenuBlockService
        arguments: ["chamilo.corebundle.block.main_menu", @templating, @knp_menu.menu_provider, @chamilo.corebundle.menu.main_menu_builder ]
        tags:
            - { name: sonata.block }

    # Breadcrumb
    chamilo.corebundle.block.breadcrumb:
        class: Chamilo\CoreBundle\Block\DefaultBreadcrumbBlockService
        arguments: ["default", "chamilo.corebundle.block.breadcrumb", @templating, @knp_menu.menu_provider, @knp_menu.factory]
        tags:
            - { name: sonata.block }
            - { name: sonata.breadcrumb }

    chamilo.userbundle.encoder:
        class: Application\Sonata\UserBundle\Security\Encoder

    # Settings
    chamilo.settings_schema.platform:
        class: Chamilo\CoreBundle\Settings\PlatformSettingsSchema
        tags:
            - { name: sylius.settings_schema, namespace: platform }

    chamilo.settings_schema.course:
        class: Chamilo\CoreBundle\Settings\CourseSettingsSchema
        tags:
            - { name: sylius.settings_schema, namespace: course }

