parameters:
    chamilo_core.manager.course.class: Chamilo\CoreBundle\Entity\CourseManager
    chamilo_core.manager.course.entity: Chamilo\CoreBundle\Entity\Course

services:
    twig.extension.chamilo_extension:
        class: Chamilo\CoreBundle\Twig\Extension\ChamiloExtension
        tags:
            - { name: twig.extension }

    chamilo_core.directory_namer.user_image:
        class: Chamilo\CoreBundle\Naming\UserImage

    chamilo_core.manager.course:
        class: %chamilo_core.manager.course.class%
        arguments: [%chamilo_core.manager.course.entity%, @doctrine]

    chamilo_core.form.type.yes_no:
        class: Chamilo\CoreBundle\Form\Type\YesNoType
        tags:
            - { name: form.type, alias: yes_no }

    chamilo_user_extra_field_value:
        class: Chamilo\UserBundle\Form\Type\AttributeValueType
        arguments: [Chamilo\CoreBundle\Entity\UserFieldValues, ["registration"], 'user']
        tags:
            - { name: form.type }

    chamilo_user_extra_field_choice:
        class: Chamilo\UserBundle\Form\Type\AttributeEntityChoiceType
        arguments: ['user', Chamilo\CoreBundle\Entity\UserField]
        tags:
            - { name: form.type }

    chamilo_core.html_editor:
        class: Chamilo\CoreBundle\Component\Editor\CkEditor\CkEditor
        arguments: [@translator, @router]

    # Listeners

#    chamilo.doctrine.entity_listener_resolver:
#        class: Chamilo\CoreBundle\Doctrine\EntityListenerResolver
#        arguments: [ "@service_container" ]

    chamilo_core.listener.online:
        class: Chamilo\CoreBundle\EventListener\OnlineListener
        arguments: [@security.context, @doctrine.orm.entity_manager ]
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: onCoreController }

    chamilo_core.listener.course:
        class: Chamilo\CoreBundle\Entity\Listener\CourseListener
        arguments: [ @chamilo_course.tool_chain ]
        tags:
            - { name: doctrine.orm.entity_listener }
#            - { name: doctrine.event_listener, event: prePersist }

    chamilo_core.listener.legacy:
        class: Chamilo\CoreBundle\EventListener\LegacyListener
        arguments: [@service_container]
        tags:
          - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest, priority: 10 }
          - { name: kernel.event_listener, event: kernel.response, method: onKernelResponse }
          - { name: kernel.event_listener, event: kernel.controller, method: onKernelController }

    chamilo_core.listener.locale:
        class: Chamilo\CoreBundle\EventListener\LocaleListener
        arguments: ["%kernel.default_locale%"]
        tags:
            - { name: kernel.event_subscriber }

    chamilo_core.listener.navbar_menu_listener:
        class: Chamilo\CoreBundle\EventListener\MenuListener
        arguments: [@service_container]
        tags:
            - { name: kernel.event_listener, event: theme.sidebar_setup_menu_knp, method: onSetupMenu }

    chamilo_core.listener.navbar_user_listener:
        class: Chamilo\CoreBundle\EventListener\ShowUserListener
        arguments: [@service_container]
        tags:
            - { name: kernel.event_listener, event: theme.navbar_user, method: onShowUser }
            - { name: kernel.event_listener, event: theme.sidebar_user, method: onShowUser }

    chamilo_core.listener.message_listener:
        class: Chamilo\CoreBundle\EventListener\MessageListener
        arguments: [@service_container]
        tags:
            - { name: kernel.event_listener, event: theme.messages, method: onListMessages }

    chamilo_core.listener.login_success_handler:
        class: Chamilo\CoreBundle\EventListener\LoginSuccessHandler
        arguments:  [@router, @security.context]

    chamilo_core.listener.logout_success_handler:
        class: Chamilo\CoreBundle\EventListener\LogoutSuccessHandler
        arguments:  [@router, @security.context]

    # ORMs
    chamilo_course.entity.course:
        class: Chamilo\CourseBundle\Entity\CourseManager
        arguments: [@doctrine]

    # Course block
    chamilo_core.block.course:
        class: Chamilo\CoreBundle\Block\CourseBlockService
        arguments: ["course_block", @templating ]
        tags:
            - { name: sonata.block }

    # Course block
    chamilo_core.block.header:
        class: Chamilo\CoreBundle\Block\CourseBlockService
        arguments: ["header", @templating ]
        tags:
            - { name: sonata.block }

    # Menus

    chamilo_core.menu.simple_menu:
        class: Chamilo\CoreBundle\Menu\SimpleMenuBuilder
        arguments: [@service_container]

    chamilo_core.menu.menu.main_menu_builder:
        class: Chamilo\CoreBundle\Menu\MainMenuBuilder
        arguments: [@knp_menu.factory, @router]

    chamilo_core.menu.menu.course_menu_builder:
        class: Chamilo\CoreBundle\Menu\CourseMenuBuilder
        arguments: [@knp_menu.factory, @chamilo_course.entity.course, @router]

    # Blocks
    chamilo_core.block.main_menu:
        class: Chamilo\CoreBundle\Block\MainMenuBlockService
        arguments: ["chamilo_core.block.menu.main_menu", @templating, @knp_menu.menu_provider, @chamilo_core.menu.menu.main_menu_builder ]
        tags:
            - { name: sonata.block }

    # Breadcrumb
    chamilo_core.block.breadcrumb:
        class: Chamilo\CoreBundle\Block\DefaultBreadcrumbBlockService
        arguments: ["default", "chamilo_core.block.breadcrumb", @templating, @knp_menu.menu_provider, @knp_menu.factory]
        tags:
            - { name: sonata.block }
            - { name: sonata.breadcrumb }

    chamilo_core.encoder:
        class: Chamilo\UserBundle\Security\Encoder
        arguments: ['%password_encryption%']

    # Settings
    chamilo_core.settings_schema.admin:
        class: Chamilo\CoreBundle\Settings\AdminSettingsSchema
        tags:
            - { name: sylius.settings_schema, namespace: admin }

    chamilo_core.settings_schema.agenda:
        class: Chamilo\CoreBundle\Settings\AgendaSettingsSchema
        tags:
            - { name: sylius.settings_schema, namespace: agenda }

    chamilo_core.settings_schema.chat:
        class: Chamilo\CoreBundle\Settings\ChatSettingsSchema
        tags:
            - { name: sylius.settings_schema, namespace: chat }

    chamilo_core.settings_schema.course:
        class: Chamilo\CoreBundle\Settings\CourseSettingsSchema
        tags:
            - { name: sylius.settings_schema, namespace: course }

    chamilo_core.settings_schema.display:
        class: Chamilo\CoreBundle\Settings\DisplaySettingsSchema
        tags:
            - { name: sylius.settings_schema, namespace: display }

    chamilo_core.settings_schema.document:
        class: Chamilo\CoreBundle\Settings\DocumentSettingsSchema
        tags:
            - { name: sylius.settings_schema, namespace: document }

    chamilo_core.settings_schema.dropbox:
        class: Chamilo\CoreBundle\Settings\DropboxSettingsSchema
        tags:
            - { name: sylius.settings_schema, namespace: dropbox }

    chamilo_core.settings_schema.editor:
            class: Chamilo\CoreBundle\Settings\EditorSettingsSchema
            tags:
                - { name: sylius.settings_schema, namespace: editor }

    chamilo_core.settings_schema.exercise:
        class: Chamilo\CoreBundle\Settings\ExerciseSettingsSchema
        tags:
            - { name: sylius.settings_schema, namespace: exercise }

    chamilo_core.settings_schema.forum:
        class: Chamilo\CoreBundle\Settings\ForumSettingsSchema
        tags:
            - { name: sylius.settings_schema, namespace: forum }

    chamilo_core.settings_schema.glossary:
        class: Chamilo\CoreBundle\Settings\GlossarySettingsSchema
        tags:
            - { name: sylius.settings_schema, namespace: glossary }

    chamilo_core.settings_schema.gradebook:
        class: Chamilo\CoreBundle\Settings\GradebookSettingsSchema
        tags:
            - { name: sylius.settings_schema, namespace: gradebook }

    chamilo_core.settings_schema.group:
        class: Chamilo\CoreBundle\Settings\GroupSettingsSchema
        tags:
            - { name: sylius.settings_schema, namespace: group }

    chamilo_core.settings_schema.mail:
        class: Chamilo\CoreBundle\Settings\MailSettingsSchema
        tags:
            - { name: sylius.settings_schema, namespace: mail }

    chamilo_core.settings_schema.message:
        class: Chamilo\CoreBundle\Settings\MessageSettingsSchema
        tags:
            - { name: sylius.settings_schema, namespace: message }

    chamilo_core.settings_schema.platform:
        class: Chamilo\CoreBundle\Settings\PlatformSettingsSchema
        tags:
            - { name: sylius.settings_schema, namespace: platform }

    chamilo_core.settings_schema.profile:
        class: Chamilo\CoreBundle\Settings\ProfileSettingsSchema
        tags:
            - { name: sylius.settings_schema, namespace: profile }

    chamilo_core.settings_schema.registration:
        class: Chamilo\CoreBundle\Settings\RegistrationSettingsSchema
        tags:
            - { name: sylius.settings_schema, namespace: registration }

    chamilo_core.settings_schema.search:
        class: Chamilo\CoreBundle\Settings\SearchSettingsSchema
        tags:
            - { name: sylius.settings_schema, namespace: search }

    chamilo_core.settings_schema.security:
        class: Chamilo\CoreBundle\Settings\SecuritySettingsSchema
        tags:
            - { name: sylius.settings_schema, namespace: security }

    chamilo_core.settings_schema.session:
        class: Chamilo\CoreBundle\Settings\SessionSettingsSchema
        tags:
            - { name: sylius.settings_schema, namespace: session }

    chamilo_core.settings_schema.skill:
        class: Chamilo\CoreBundle\Settings\SkillSettingsSchema
        tags:
            - { name: sylius.settings_schema, namespace: skill }

    chamilo_core.settings_schema.social:
        class: Chamilo\CoreBundle\Settings\SocialSettingsSchema
        tags:
            - { name: sylius.settings_schema, namespace: social }

    chamilo_core.settings_schema.survey:
        class: Chamilo\CoreBundle\Settings\SurveySettingsSchema
        tags:
            - { name: sylius.settings_schema, namespace: survey }

    chamilo_core.settings_schema.tracking:
        class: Chamilo\CoreBundle\Settings\TrackingSettingsSchema
        tags:
            - { name: sylius.settings_schema, namespace: tracking }
