services:
    sonata.admin.contact_category:
        class: Chamilo\ContactBundle\Admin\CategoryAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "LMS", label: "ContactCategory" }
        arguments:
            - ~
            - Chamilo\ContactBundle\Entity\Category.php
            - ~
