parameters:
    chamilo_installer.form.type.configuration.class:          ChamiloLMS\InstallerBundle\Form\Type\ConfigurationType
    chamilo_installer.form.type.configuration.database.class: ChamiloLMS\InstallerBundle\Form\Type\Configuration\DatabaseType
    chamilo_installer.form.type.configuration.mailer.class:   ChamiloLMS\InstallerBundle\Form\Type\Configuration\MailerType
    chamilo_installer.form.type.configuration.system.class:   ChamiloLMS\InstallerBundle\Form\Type\Configuration\SystemType
#    chamilo_installer.form.type.configuration.ws.class:       ChamiloLMS\InstallerBundle\Form\Type\Configuration\WebsocketType
    chamilo_installer.form.type.setup.class:                  ChamiloLMS\InstallerBundle\Form\Type\SetupType

services:
    chamilo_installer.form.type.configuration:
        class:                                            %chamilo_installer.form.type.configuration.class%
        tags:
            - { name: form.type, alias: chamilo_installer_configuration }

    chamilo_installer.form.type.configuration.database:
        class:                                            %chamilo_installer.form.type.configuration.database.class%
        tags:
            - { name: form.type, alias: chamilo_installer_configuration_database }

    chamilo_installer.form.type.configuration.mailer:
        class:                                            %chamilo_installer.form.type.configuration.mailer.class%
        tags:
            - { name: form.type, alias: chamilo_installer_configuration_mailer }

    chamilo_installer.form.type.configuration.system:
        class:                                            %chamilo_installer.form.type.configuration.system.class%
        tags:
            - { name: form.type, alias: chamilo_installer_configuration_system }

#    chamilo_installer.form.type.configuration.websocket:
#        class:                                            %chamilo_installer.form.type.configuration.ws.class%
#        tags:
#            - { name: form.type, alias: chamilo_installer_configuration_websocket }

    chamilo_installer.form.type.setup:
        class:                                            %chamilo_installer.form.type.setup.class%
        arguments:
            - Application\Sonata\UserBundle\Entity\User
        tags:
            - { name: form.type, alias: chamilo_installer_setup }
