services:
    sonata.admin.course:
        class: ChamiloLMS\CoreBundle\Admin\CourseAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "LMS", label: "Course" }
        arguments:
            - ~
            - ChamiloLMS\CoreBundle\Entity\Course
            - ~
        calls:
            - [ setTranslationDomain, [ChamiloLMSCoreBundle]]
            - [ setToolChain, [@chamilolms.tool_chain]]

    sonata.admin.session:
        class: ChamiloLMS\CoreBundle\Admin\SessionAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "LMS", label: "Session" }
        arguments:
            - ~
            - ChamiloLMS\CoreBundle\Entity\Session
            - ~
        calls:
            - [ setTranslationDomain, [ChamiloLMSCoreBundle]]

    sonata.admin.course_rel_user:
          class: ChamiloLMS\CoreBundle\Admin\CourseRelUserAdmin
          tags:
              - { name: sonata.admin, manager_type: orm, group: "LMS", label: "CourseRelUser" }
          arguments:
              - ~
              - ChamiloLMS\CoreBundle\Entity\CourseRelUser
              - ~
          calls:
              - [ setTranslationDomain, [ChamiloLMSCoreBundle]]

    sonata.admin.session_rel_course:
          class: ChamiloLMS\CoreBundle\Admin\SessionRelCourseAdmin
          tags:
              - { name: sonata.admin, manager_type: orm, group: "LMS", label: "SessionRelCourseAdmin" }
          arguments:
              - ~
              - ChamiloLMS\CoreBundle\Entity\SessionRelCourse
              - ~
          calls:
              - [ setTranslationDomain, [ChamiloLMSCoreBundle]]

    sonata.admin.access_url:
          class: ChamiloLMS\CoreBundle\Admin\AccessUrlAdmin
          tags:
              - { name: sonata.admin, manager_type: orm, group: "LMS", label: "AccessUrlAdmin" }
          arguments:
              - ~
              - ChamiloLMS\CoreBundle\Entity\AccessUrl
              - ~
          calls:
              - [ setTranslationDomain, [ChamiloLMSCoreBundle]]

    sonata.admin.access_url_rel_course:
          class: ChamiloLMS\CoreBundle\Admin\AccessUrlRelCourseAdmin
          tags:
              - { name: sonata.admin, manager_type: orm, group: "LMS", label: "AccessUrlRelCourseAdmin" }
          arguments:
              - ~
              - ChamiloLMS\CoreBundle\Entity\AccessUrlRelCourse
              - ~
          calls:
              - [ setTranslationDomain, [ChamiloLMSCoreBundle]]

