index:
    resource: "@ChamiloLMSCoreBundle/Controller/IndexController.php"
    type:     annotation
    prefix:   /

# legacy routes
main:
    path:     /main/{name}
    defaults: { _controller: ChamiloLMSCoreBundle:Legacy:classic }
    requirements:
      name: .+

# web url shortcuts
web.ajax:
    path: main/inc/ajax/

web.main:
    path: main/

web.img:
    path: bundles/chamilolmscore/img/

# core controllers

core_admin:
    resource: "@ChamiloLMSCoreBundle/Controller/Admin"
    type: annotation
    prefix:   /admin

core_app:
    resource: "@ChamiloLMSCoreBundle/Controller/App"
    type: annotation
    prefix:   /app

core_tool:
    resource: "@ChamiloLMSCourseBundle/Controller"
    type: annotation
    prefix: /courses/{course}/

# redirects /url/ to /url

remove_trailing_slash:
    path: /{url}
    defaults: { _controller: ChamiloLMSCoreBundle:Redirecting:removeTrailingSlash }
    requirements:
        url: .*/$
        _method: GET
