services:

    sonata.admin.faq_question:
        class: Chamilo\FaqBundle\Admin\QuestionAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Content", label: "FAQ" }
        arguments:
            - ~
            - Chamilo\FaqBundle\Entity\Question
            - ~

    sonata.admin.faq_category:
        class: Chamilo\FaqBundle\Admin\CategoryAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Content", label: "FAQ category" }
        arguments:
            - ~
            - Chamilo\FaqBundle\Entity\Category
            - ~
