name: PHP Composer

on: [push, pull_request]

jobs:
    build:
        name: PHP ${{ matrix.php-versions }} Test on ${{ matrix.operating-system }}
        runs-on: ubuntu-latest

        strategy:
            fail-fast: false
            matrix:
                operating-system: [ubuntu-latest]
                php-versions: ['7.3', '7.4', '8.0']

        services:
            mysql:
                image: mysql:5.7
                env:
                    MYSQL_ALLOW_EMPTY_PASSWORD: false
                    MYSQL_ROOT_PASSWORD: chamilo
                    MYSQL_DATABASE: chamilo
                ports:
                    - 3306
                options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

        steps:
            - name: Checkout
              uses: actions/checkout@v1

            - name: Setup PHP, with composer and extensions
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php-versions }}
                  tools: behat
                  extensions: mbstring, xml, ctype, iconv, mysql, gd, soap, intl, zip, bcmath

            -  name: Start mysql service
               run: sudo /etc/init.d/mysql start

            - name: Install dependencies
              run: composer install --prefer-dist --no-progress --no-suggest --no-scripts

            - name: Run Migration
              run: |
                  php bin/console doctrine:database:create || echo "Create schema"

              env:
                DATABASE_URL: mysql://root:chamilo@127.0.0.1:${{ job.services.mysql.ports['3306'] }}/chamilo
                APP_INSTALLED: 1

            - name: Composer analyse
              run: composer analyse

        # Add a test script to composer.json, for instance: "test": "vendor/bin/phpunit"
        # Docs: https://getcomposer.org/doc/articles/scripts.md

        # - name: Run test suite
        #   run: composer run-script test
